### ISSUE TITLE
Jump to speaker's twitter profile

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#106]
**Describe the idea**
Jump to speaker's twitter profile page with tapped speaker name in session detail screen

**Reference images and links**
![image](https://user-images.githubusercontent.com/38175830/188250078-a431252e-ae35-40da-8b7d-5e7a5c352bf7.png)

[Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App)

**Comment by usuiat** [comment]
🙋 I want to take this issue.

**Comment by takahirom** [comment]
Thanks! Assigned 🐦

**Comment by usuiat** [comment]
Let me ask a question.
How can I get the speaker's twitter user name?
I thought the text displayed next to the speaker's image was the twitter user name, but it wasn't.
Is adding a process to get twitter user names from the server also in scope for this issue?

**Comment by takahirom** [comment]
Sorry. I think it is impossible because there is no data related to Twitter. 🙇 
Let me close this issue.
