### ISSUE TITLE
Match the color of the app to the color of the Status bar

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#111]
**Describe the idea**

You can check the image.
The current app is above. And the design is under.

**Reference images and links**
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App?node-id=0%3A1
![image](https://user-images.githubusercontent.com/1386930/188258835-2dd46e38-e77f-4afe-b927-ad394c99f65e.png)

**Comment by Kaito-Dogi** [comment]
🙋‍♂️
