### ISSUE TITLE
Add benchmark module for measuring launch performance

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#112]
**Describe the idea**
If we add the benchmark module, we can check the launch performance. And we can introduce the baseline profile.
The goal is to add a module that can measure launch performance.

**Reference images and links**
https://github.com/android/nowinandroid/tree/main/benchmark

**Comment by hiraok** [comment]
🙌

**Comment by takahirom** [comment]
Thanks! Assigned 📊

**Comment by takahirom** [comment]
@hiraok This issue has a blocking task. Can you do it?

**Comment by hiraok** [comment]
@takahirom Sorry this is late..  I’ll take care of it 👍
