### ISSUE TITLE
Make KaigiTag slot API pattern 🎰 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#114]
**Describe the idea**
Currently, we are passing parameters expressly like `text: String` . But if we can use label: @[Composable](https://developer.android.com/reference/kotlin/androidx/compose/runtime/Composable) () -> [Unit](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-unit/index.html), we can also add image in it. I think it will be more flexible.

And in the KaigiTag composable, I think we can add CompositionLocalProvider to adapt the text design. 🎨 

```kotlin
    CompositionLocalProvider(
        LocalContentColor provides labelColor,
        LocalTextStyle provides labelTextStyle
    ) {
      label()
```

**Reference images and links**

* What is Slot API pattern?
You can learn Slot API Pattern here.
https://chris.banes.dev/slotting-in-with-compose-ui/

* What is KaigiTag?

![image](https://user-images.githubusercontent.com/1386930/188259252-568d3a61-9570-4503-b58e-8a7a069c5894.png)

https://github.com/DroidKaigi/conference-app-2022/blob/789e2f715776a2e30bef68442c52a2a13018ce36/core-designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/designsystem/components/KaigiTag.kt#L21

* You can also use Material3 chip as a reference.

https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#AssistChip(kotlin.Function0,kotlin.Function0,androidx.compose.ui.Modifier,kotlin.Boolean,kotlin.Function0,kotlin.Function0,androidx.compose.ui.graphics.Shape,androidx.compose.material3.ChipColors,androidx.compose.material3.ChipElevation,androidx.compose.material3.ChipBorder,androidx.compose.foundation.interaction.MutableInteractionSource)

**Comment by r4wxii** [comment]
i'll try this 🙋

**Comment by tomoya0x00** [comment]
Could you handle it? Assigned 👍

**Comment by r4wxii** [comment]
What about making the label a RowScope instead of just a Composable?
I think most icons are lined up in Row.
Calling Row inside a KaigiTag allows for more flexibility while maintaining a consistent look 🤔
```kotlin
@Composable
fun KaigiTag(
    label: @Composable RowScope.() -> Unit
) {
    Row {
        label()
    }
}
```

**Comment by takahirom** [comment]
@r4wxii It would be better!
