### ISSUE TITLE
Make a navigation drawer divider by group

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#124]
**Idea Description**
Make DrawerGroup and add it in DrawerItem for inserting divider.
like this, 
```kotlin
DrawerItem.Sessions(DrawerGroup.Session, R.string.title_sessions, Icons.Default.Event, SessionsNavGraph.sessionRoute),
```

Currently, this feature is implemented by a if statement in NavigationDrawerItem 
```kotlin
if (drawerItem == DrawerItem.Sessions || drawerItem == DrawerItem.Map) {
```

**Reference images and links**
- [Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App)

screenshot
<img src="https://user-images.githubusercontent.com/38175830/188292772-19547fc7-3ca0-4013-b093-fbcbd745bcc3.png" width = 40% />

**Comment by Kaito-Dogi** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned ➗

**Comment by takahirom** [comment]
@Kaito-Dogi How's it going?

**Comment by Kaito-Dogi** [comment]
@takahirom 
Sorry for the delay, got caught up in figuring out how to implement this, sorry!
I have submitted a pull request #542 , please check back.
