### ISSUE TITLE
Round the corner of the ripple effect when timeTable day tabs are clicked

### ISSUE THREAD

**Issue by kokoakuma** [DroidKaigi/conference-app-2022#126]
**Idea Description**
Currently, rippling the background of timetable day tabs fills it in as a rectangle,
but we would like to make it rounded.

**Reference images and links**

- [figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App?node-id=20%3A570)

the screenshot of the ripple effect on the day tabs in its current state
![InkedScreenshot_20220904_100433_2](https://user-images.githubusercontent.com/40256933/188293979-69730c18-90b5-46de-9e41-dd18a42e82cd.jpg)

**Comment by l2hyunwoo** [comment]
Can I take this issue?

**Comment by takahirom** [comment]
You are the first one who takes the issue! Off course! Assigned 🏎️

**Comment by Nthily** [comment]
@l2hyunwoo I'm sorry I didn't see this issue, I saw the ripple problem when I first built the app, so I just modified it and submitted the PR, sorry about that. 🙏🙏🙏

**Comment by l2hyunwoo** [comment]
@Nthily It's ok :) Never mind!
