### ISSUE TITLE
Add "Kaigi" to IDE dictionary

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#133]
**Idea Description**

**Reference images and links**
<img width="202" alt="image" src="https://user-images.githubusercontent.com/1386930/188304683-e53b03dd-63f0-4c0d-9e71-8a333b32a09d.png">

**Comment by toastmeister1** [comment]
I'd add this!

**Comment by takahirom** [comment]
Thanks! I'm looking forward to seeing your PR!
