### ISSUE TITLE
Add compose compiler metrics option

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#142]
**Idea Description**
Please add option to add compose compiler metrics.

**Reference images and links**
https://github.com/androidx/androidx/blob/androidx-main/compose/compiler/design/compiler-metrics.md
https://github.com/android/nowinandroid/pull/125

**Comment by MasahiroLittleforest** [comment]
I want to take this issue🙋

**Comment by takahirom** [comment]
Thanks!Assigned!

**Comment by MasahiroLittleforest** [comment]
I have some questions.

1. In which modules do I need to enable the metrics?
2. Where should the reports be written? under build?

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
1. Can you use compose plugin in bulid-logic?
2. Please put it in bulid/
You can check my pr in nowinandroid🙏
