### ISSUE TITLE
Add padding bottom of day tab

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#157]
**Idea Description**

![image](https://user-images.githubusercontent.com/1386930/188347363-b0e56975-a90c-4cc9-bebd-e3dd5dfaab88.png)

**Reference images and links**
Design Kit
https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=11%3A1833
App Design
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by mona-apk** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned! I tried once, but I can't do it😂
