### ISSUE TITLE
Fix day title size

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#158]
**Idea Description**

**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/188348318-1a3add59-0e55-49d0-ace2-f5b6b4078a4e.png)
Design Kit
https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=11%3A1833
App Design
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by okuzawats** [comment]
I'd fix this🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by okuzawats** [comment]
@takahirom I created a PR. Please check it out. #196
