### ISSUE TITLE
add read more to description in Session Detail Screen

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#159]
**Idea Description**
add read more to description in Session Detail Screen

**Reference images and links**
<img src="https://user-images.githubusercontent.com/60292683/188349294-76027ffe-3067-4b22-afe3-344f4641e5cb.png" width="300">

Design Kit
https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=11%3A1833
App Design
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by kota-shiokara** [comment]
I want to try this issue

**Comment by sobaya-0141** [comment]
Thanks! Assigned
