### ISSUE TITLE
add TagsLine in session detail Screen

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#160]
**Idea Description**
use KaigiTag  slot api

**Reference images and links**
Design
<img src="https://user-images.githubusercontent.com/60292683/188349438-4aacd5c9-aded-4be8-a9e4-48d00ff64dd8.png" width="300" >
Current app
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1386930/188361924-415feb15-db3e-4fca-9210-fecb4697ff72.png">

Design Kit
https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=11%3A1833
App Design
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by ao0000** [comment]
🙋

**Comment by sobaya-0141** [comment]
Thanks! Assigned 👍
