### ISSUE TITLE
add Icon and fix design assets section in session detail screen

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#161]
**Idea Description**

-  when items tapped , open url 

**Reference images and links**
<img src="https://user-images.githubusercontent.com/60292683/188349606-c69093dc-fb5d-43c6-b8d0-30ee6db7c1e0.png" width="300">

Design Kit
https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=11%3A1833
App Design
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by blackbracken** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned
