### ISSUE TITLE
add bottom navigation view in session detail screen

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#164]
**Idea Description**

- share
- scroll to top
- favorite
  - when tapped set favorite button toggled

**Reference images and links**

<img src="https://user-images.githubusercontent.com/60292683/188351026-128eab39-e8a4-46f0-a8de-661472ce468f.png" width="300">

Design Kit
https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=11%3A1833
App Design
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by takahirom** [comment]
I think it is important to be able to favorite the session.
So I think we just need to implement the favorite button at first.

**Comment by takahirom** [comment]
I added the favorite button.

**Comment by KoutaMatsushita** [comment]
🙋

**Comment by takahirom** [comment]
@KoutaMatsushita 
Thanks!
Let me correct the discription 🙏 

- share
- ~scroll to top~ Go to the floor map screen
- Register the schedule to Google calendar.
