### ISSUE TITLE
fix back to sessions list or timelines from session detail screen

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#165]
**Idea Description**
when navigation button tapped , back to timelines

**Reference images and links**
<img src="https://user-images.githubusercontent.com/60292683/188351355-34529b00-d1e4-4c51-9a57-1de06dc49f3b.png" width="300">

Design Kit
https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=11%3A1833
App Design
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by l2hyunwoo** [comment]
I'd like to take this issue after [this issue](https://github.com/DroidKaigi/conference-app-2022/issues/171) merge!

**Comment by l2hyunwoo** [comment]
I'll take it :)
