### ISSUE TITLE
fix term design  in session detail screen

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#169]
**Idea Description**
- set Icon
- fix term design like "10月7日11:00 - 11:20 " 

**Reference images and links**

current app | design
------ | ------
<img src="https://user-images.githubusercontent.com/60292683/188353873-cebfda8d-0947-4da3-887a-9861fc7a3b5b.png" width="300" > | <img src="https://user-images.githubusercontent.com/60292683/188352855-d14cbfdc-d533-4062-9d19-7b07dc082ee8.png" width="300" >

Design Kit
https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=11%3A1833
App Design
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by l2hyunwoo** [comment]
Can I take this issue?

**Comment by takahirom** [comment]
Thanks! Assigned! If I review this PR, I will check if it is you 🙏
