### ISSUE TITLE
Navigate from sessions list to session's detail

### ISSUE THREAD

**Issue by t-yusaku** [DroidKaigi/conference-app-2022#170]
**Idea Description**

**Reference images and links**
Sessions List | Session Detail
:--: | :--:
<img src="https://user-images.githubusercontent.com/58973616/188353552-c390a403-a75a-4411-8fd7-66a390f73b63.png" width="300" /> | <img src="https://user-images.githubusercontent.com/58973616/188353578-c34636e6-a43d-48ef-9e2f-6155ebc75ffb.png" width="300" />

**Comment by Pluu** [comment]
🙋

Since the navigation icon is not exposed as X even in the timetable format, we will omit it in this work.
