### ISSUE TITLE
fix layout in session detail screen

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#171]
**Idea Description**
set padding and marigins( fixing icons or features is other issue)

**Reference images and links**

current app | design
------ | ------
<img src="https://user-images.githubusercontent.com/60292683/188243396-67bc0c95-5a62-47dc-97ce-b253276643ea.png" width="300"> | <img src="https://user-images.githubusercontent.com/1386930/188352238-113d8f15-7b06-4255-9dea-ccfff53d19c0.png"  width="300">

Design Kit
https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=11%3A1833
App Design
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by ttanaka330** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned📝

**Comment by ttanaka330** [comment]
In Figma, the horizontal end is 17dp, but is 16dp okay?

<img width="400" src="https://user-images.githubusercontent.com/31527039/188482314-64ebf1f1-1417-4739-a31c-330566d94355.png">

**Comment by takahirom** [comment]
I think it is 16dp too. I'll ask the designer.

**Comment by takahirom** [comment]
I confirmed that it is 16dp 🙏
