### ISSUE TITLE
create Search Screen without design

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#172]
**Idea Description**
- create  only search screen without design 
-  fill in name , filtered list shows
-  issue devided apply design 

**Reference images and links**
design coming soon

**Comment by mtkw0127** [comment]
I’d like to try this issue 💪

**Comment by sobaya-0141** [comment]
Thanks! Assigned :+1:

**Comment by mtkw0127** [comment]
@sobaya-0141 
I couldn't show time schedule screen like below.
Android Studio shows the error in [Logcat](https://gist.github.com/mtkw0127/59469649da54167782cdf55545ad9bb5).

If I changed description field of SessionResponse.kt nullable, I can see time table.
Dou you see the table? This is only me?

<img src="https://user-images.githubusercontent.com/36796492/188765221-b8f69e46-2a3e-404b-aa45-1e991933b9ee.png" width="200px"/>

**Comment by sobaya-0141** [comment]
I believe this is being addressed by #246.
Could you try to update it?

**Comment by mtkw0127** [comment]
@sobaya-0141 
I could run latest main branch. Thank you 👍 

I'm junior level developer. so I want to question 😭 
speakers is common field Session and Special in TimetableItem.kt.
speakers field move to TimetableItem seald class as abstract field？？

**Comment by takahirom** [comment]
You can create draft to align implementation policies before you spend a lot of time. 👍I'm rooting for you.

I think we can implement the seach() method in Timetable class.
And we can implement it by abstract isMatch(query) in TimetableItem and implement it in Special and Session.
