### ISSUE TITLE
create  notification screen without design

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#174]
**Idea Description**
create  notification screen without design

issue devided apply design

**Reference images and links**
coming soon

**Comment by sadashi-ota** [comment]
I want to try it! 🙋‍♂️ 
Is this an announcement screen?

**Comment by sobaya-0141** [comment]
Thanks! Assigned :+1:

**Comment by sadashi-ota** [comment]
Thx.

>Is this an announcement screen?

How about this?
You mean the notation fluctuation of announcements, informations, and notifications, right?

**Comment by sadashi-ota** [comment]
I understood the `notification screen` as `information screen` and implemented.
tell me if i'm wrong
