### ISSUE TITLE
Implement announcement screen

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#175]
**Idea Description**
apply notification screen design

**Reference images and links**
coming soon

**Comment by l2hyunwoo** [comment]
Will the design of the announcement screen be released?

**Comment by takahirom** [comment]
@l2hyunwoo I believe so 🎨

**Comment by takahirom** [comment]
The design is added!
<img width="217" alt="image" src="https://user-images.githubusercontent.com/1386930/190940343-7316eed4-2782-4491-aca2-d7d60491744c.png">

**Comment by takahirom** [comment]
There is a Screen root composable. But there isn't ViewModel and repository
https://github.com/DroidKaigi/conference-app-2022/blob/main/feature/announcement/src/main/java/io/github/droidkaigi/confsched2022/feature/announcement/Announcement.kt

**Comment by takahirom** [comment]
This is the API and sample response.

https://ssot-api-staging.an.r.appspot.com/announcements/japanese

```
{
  "status": "string",
  "announcements": [
    {
      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
      "title": "string",
      "content": "string",
      "type": "ALERT",
      "publishedAt": "string",
      "deletedAt": "string",
      "language": "japanese"
    }
  ]
}
```

**Comment by takahirom** [comment]
You can refer to other screens' implementations.
https://github.com/DroidKaigi/conference-app-2022/pull/331

**Comment by Corvus400** [comment]
I would like to start on this task.

**Comment by Corvus400** [comment]
@takahirom 
I have a question.🙋‍♂️
If I apply the API response and my understanding, it looks like the image.
How do you expect to use `deletedAt` and `Language`?
![スクリーンショット 2022-09-20 11 07](https://user-images.githubusercontent.com/13657682/191152601-4deaca2c-bc15-40a8-a531-4b75a1fbb9dc.png)

**Comment by takahirom** [comment]
Thank you for your detailed image! I think you don't have to use it.
The fields are for the server side.
You can access by language, so there it is. But I think we don't have to use it.
And if there is deleteAt field, Please filter it in API or repository it is not for the client.
https://ssot-api-staging.an.r.appspot.com/announcements/japanese
https://ssot-api-staging.an.r.appspot.com/announcements/english

@RyuNen344 Is this correct?

**Comment by RyuNen344** [comment]
@takahirom @Corvus400 

sorry for late 🙏 
announcement end points returns json like this👇

```json5
{
  "status": "string",
  "announcements": [
    {
      "id": "497f6eca-6276-4993-bfeb-53cbbbba6f08",
      "title": "string",
      "content": "string",
      "type": "ALERT", //ALERT, NOTIFICATION, FEEDBACK
      "publishedAt": "string", //ISO-8601-datetime
      "language": "japanese"
    }
  ]
}
```

so, client doen't filter item by `deletedAt`

**Comment by Corvus400** [comment]
@takahirom 
Just to confirm, there is no need to store data in the DB, right?
I assume the same is true for contributors and sponsors since they are not stored in the DB.

**Comment by takahirom** [comment]
@Corvus400 I think there is no need too!
