### ISSUE TITLE
create floor map  screen 

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#176]
**Idea Description**
create floor map  screen without design

issue devided apply design

**Reference images and links**
coming soon

**Comment by takahirom** [comment]
I think there isn't a design now, so just do this. 🙏 
https://github.com/DroidKaigi/conference-app-2022/pull/129

**Comment by Nthily** [comment]
Can i take this issue?

**Comment by takahirom** [comment]
Of course! Thanks as always. Assigned 👍
