### ISSUE TITLE
create setting screen 

### ISSUE THREAD

**Issue by cOnigashima** [DroidKaigi/conference-app-2022#180]
**Idea Description**
create setting screen 

**Reference images and links**
coming soon

**Comment by obaya884** [comment]
Can I try this issue? :eyes:

We don't have design instructions in figma yet, but [referring to the DroidKaigi 2021 app](https://www.figma.com/file/IFlrbfmBSdYvUz7VmSzfLV/DroidKaigi_2021_official_app?node-id=905%3A3066),
we could be able to implement dark mode and language setting(#192) features on this screen.

In this issue,  I am going to create the screen and just place switch composable like the 2021 app.

**Comment by takahirom** [comment]
@obaya884 Sorry for being late. Do you still want to take this issue?

**Comment by takahirom** [comment]
I think it is great!

**Comment by obaya884** [comment]
Sure, I will try!
