### ISSUE TITLE
Apply about screen design

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#181]
**Idea Description**
please apply cool design for about screen following figma instruction.

**Reference images and links**
[Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App?node-id=0%3A1)

**Comment by takahirom** [comment]
I think there is a lot of misunderstanding about this issue.
This issue is for the whole screen design. And the other issues are just for click listeners.

**Comment by Corvus400** [comment]
I would like to do this task.

**Comment by sobaya-0141** [comment]
Thanks! Assigned 👍

**Comment by Corvus400** [comment]
Sorry, as stated in the [PR summary section](https://github.com/DroidKaigi/conference-app-2022/pull/215), some of the implementation is still incomplete. 🙇‍♂️
