### ISSUE TITLE
Always display NavigationDrawer when expanded width

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2022#182]
**Idea Description**
- Always display NavigationDrawer when Window size class is expanded width.

**Reference images and links**
- https://developer.android.com/guide/topics/large-screens/navigation-for-responsive-uis

**Comment by kafumi** [comment]
Could I try this task? 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! I'm looking forward to your PR!
