### ISSUE TITLE
Jump to DroidKaigi's Youtube from the about screen

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#185]
**Idea Description**
Jump to [DroidKaigi's Youtube page](https://www.youtube.com/c/DroidKaigi) with tapped youtube icon in the about screen

blocked by #181 

**Reference images and links**
<img src="https://user-images.githubusercontent.com/38175830/188361874-334054f7-0c27-4215-b40d-c546f61ee2ef.png" width=40% />

**Comment by Corvus400** [comment]
I would like to do this task.

**Comment by takahirom** [comment]
Thanks!
