### ISSUE TITLE
show app version in the about screen

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#186]
**Idea Description**
please show app version at the bottom of the about screen 

blocked by #181 

**Reference images and links**
[Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App?node-id=0%3A1)
![about-screenのコピー3](https://user-images.githubusercontent.com/38175830/188365055-472f73ca-e54a-4654-a601-91148e084cff.png)

**Comment by l2hyunwoo** [comment]
I want to take this issue!

**Comment by takahirom** [comment]
Thanks Assigned 👍
