### ISSUE TITLE
Open the venue information by Google map from the about screen

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#187]
**Idea Description**
Open the off-line venue information by Google map from the about screen.

DroidKaigi 2022 is scheduled to be held here!
https://goo.gl/maps/NnqJr2zUVdrAJseH7

blocked by #181 

**Reference images and links**
[Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App?node-id=448%3A2009)
![about-screenのコピー](https://user-images.githubusercontent.com/38175830/188365029-e17c61da-f24f-4eb8-951c-bc77cd030d71.png)

**Comment by yoshida0261** [comment]
I want to take this issue!

**Comment by takahirom** [comment]
Thanks! Assigned 👍 
Please read this comment first 🙏  https://github.com/DroidKaigi/conference-app-2022/issues/181#issuecomment-1237317183
