### ISSUE TITLE
Show privacy policy from the about screen with web link

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#188]
**Idea Description**
Show privacy policy from the about screen with web link.
https://portal.droidkaigi.jp/about/privacy

blocked by #181

**Reference images and links**
[Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App?node-id=448%3A2009)
![about-screenのコピー2](https://user-images.githubusercontent.com/38175830/188364964-25bba3ed-d1d7-4847-a990-d3ddad923b92.png)

**Comment by YagiRyu** [comment]
🖐

**Comment by misuzz** [comment]
May I challenge this task?

**Comment by misuzz** [comment]
Thank you!
