### ISSUE TITLE
Show code of conduct from the about screen with web link

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#189]
**Idea Description**
Show privacy policy from the about screen with web link.
https://portal.droidkaigi.jp/about/code-of-conduct

blocked by #181

**Reference images and links**
[Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App?node-id=448%3A2009)

**Comment by att55** [comment]
I would like to do this task 🙋

**Comment by RyuNen344** [comment]
thanks! assined!

**Comment by att55** [comment]
@obaya884 @RyuNen344 
Please let me confirm on thing 🙏🏼 

In this issue, which web link should I use?

1. code of conduct : the title of this issue is as follows.
> Show code of conduct from the about screen with web link
https://portal.droidkaigi.jp/about/code-of-conduct

2. privacy policy : the Idea Description of this issue is as follows.
> Show privacy policy from the about screen with web link.
https://portal.droidkaigi.jp/about/privacy

**Comment by takahirom** [comment]
We are talking about this issue. Please wait🙏

**Comment by att55** [comment]
@takahirom OK, thank you for your reply!

**Comment by takahirom** [comment]
@att55 We want to add the "code of conduct" item to use this icon. Can you add it?
https://fonts.google.com/icons?icon.query=Directions+Walk

**Comment by att55** [comment]
@takahirom OK. I will add it for "code of conduct". How's the "privacy"?

**Comment by att55** [comment]
@takahirom Sorry, please let me confirm one thing 🙏🏼 
Is the position of "code of conduct" bottom (under "license") in about screen?
<img width="50%" alt="スクリーンショット 2022-09-13 18 41 10" src="https://user-images.githubusercontent.com/25548003/189868599-307ab68d-6531-4257-915c-b75d0a52b5c8.png">
