### ISSUE TITLE
Add staffs screen with design

### ISSUE THREAD

**Issue by obaya884** [DroidKaigi/conference-app-2022#190]
**Idea Description**
Please add staffs screen and make it possible to transition from the about screen.

There is no figma design for this screen, but it is assumed to be similar to the contributors screen.

**Reference images and links**
[Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/Conference-App?node-id=448%3A2009)
![about-screen](https://user-images.githubusercontent.com/38175830/188364811-724612be-a227-44a8-87bd-87a009605f61.png)

**Comment by t-nonomura** [comment]
🙋‍♂️

**Comment by sobaya-0141** [comment]
Thanks! Assigned :+1:
