### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by tomoya0x00** [DroidKaigi/conference-app-2022#195]
**Describe the bug**

molecule link and zipline link are not working correctly.

It seems the text and the URL are incorrectly swapped.

![image](https://user-images.githubusercontent.com/5106629/188467934-e3b9a450-f680-477a-b068-56328f15ff63.png)

![image](https://user-images.githubusercontent.com/5106629/188467967-dacbd632-36ed-467b-8ff0-99696453bd2b.png)

**To Reproduce**
1. Click the molecule link or zipline link in README
2. We will see a 404 error page

**Expected behavior**

The links work fine

**Screenshots**

![image](https://user-images.githubusercontent.com/5106629/188467030-a2f59015-02d0-4b4f-ba59-982e28347d86.png)

![image](https://user-images.githubusercontent.com/5106629/188467050-e89c7753-ca55-4722-ade6-0b70016d37e2.png)

**Comment by takahirom** [comment]
👀

**Comment by tomoya0x00** [comment]
Fixed by https://github.com/DroidKaigi/conference-app-2022/pull/197
Thanks @tshion 👍
