### ISSUE TITLE
Timetable room header

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#205]
**Idea Description**
The timetable code is here
https://github.com/DroidKaigi/conference-app-2022/blob/main/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/Timetable.kt
**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/188489926-967785de-0c00-4272-927e-4ad2a4a7a3dd.png)

**Comment by surajsau** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned!
