### ISSUE TITLE
Make ExternalServices camel case

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#217]
**Idea Description**
TWITTER -> Twitter
https://github.com/Corvus400/conference-app-2022/blob/ad56603e25c62199866e3a7405484989fbdb61c2/feature-about/src/main/java/io/github/droidkaigi/confsched2022/feature/about/ExternalServices.kt#L9

**Reference images and links**
https://github.com/androidx/androidx/blob/androidx-main/compose/docs/compose-api-guidelines.md#singletons-constants-sealed-class-and-enum-class-values

**Comment by obaya884** [comment]
🙋‍♂️ I want to take this issue.

**Comment by takahirom** [comment]
Thanks! Assigned 👍
