### ISSUE TITLE
Run CI with pull requests from forked repositories

### ISSUE THREAD

**Issue by hkusu** [DroidKaigi/conference-app-2022#222]
**Idea Description**

Probably works using `pull_request_target` event in `Build.yml`

**Reference images and links**

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thank you for telling me this. Let me think it over 🙏

**Comment by takahirom** [comment]
I think it is difficult to use correctly 😅 
If we introduce it, and you write something in build.gradle. Our CI will run it and print variables. 😭 
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by hkusu** [comment]
OK, I understand.

There may be no danger if you use labels like below.

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
> Add a condition to the pull_request_target to run only if a certain label is assigned the PR, like safe to test that indicates the PR has been vetted by someone with write privileges to the target repository:

Please let me know if there is an opportunity to introduce 😄
