### ISSUE TITLE
Move currentStartTime variable into remember{}

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#227]
**Idea Description**
Just move it in 🙏 
https://github.com/DroidKaigi/conference-app-2022/blob/a03690dcc290e26ffe7e00c9de4f2675a126ae3d/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/Sessions.kt#L200-L202

**Reference images and links**

**Comment by minibugdev** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned🙏
