### ISSUE TITLE
Move raw text to strings.xml in SessionDetail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#229]
**Idea Description**
The title says everything. 
Please add values-en/strings.xml too, if possible.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SessionDetail.kt#L317

**Comment by yuheikawakami** [comment]
🙋‍♂️
