### ISSUE TITLE
Replace montserrat font resource with downloadable font

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2022#230]
**Idea Description**
- Replace montserrat's font resource with downloadable font.
- And want to add the weight of the font with W500 and W400 when making downloadable font.  

**Reference images and links**
- https://developer.android.com/jetpack/compose/text#downloadable-fonts
- https://www.figma.com/file/XsVzpDZSkEQANgCZLRTDDy/DroidKaigi-2022-Material-3-Design-Kit?node-id=51510%3A8890

**Comment by risako070310** [comment]
I want to try this issue 🙋🏻‍♀️

**Comment by takahirom** [comment]
Thanks! Assigned!🙏

**Comment by risako070310** [comment]
@takahirom
I think this issue is to change the montserrat font in the Typography of KaigiTheme to a downloadable font, but KaigiTheme.typography is never used in this app I think so. Why is MaterialTheme.typography used in view?
Which is the appropriate definition for downloadable font?

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
Thanks for inquiring! Please feel free to ask me anything.
This app uses this theme throughout the app by specifying the theme here.
In MaterialTheme, the theme specified in the parent Composable of Compose can be used in the child Composable.
For example, MaterialTheme.typography.titleLarge is used in SessionListItem. This should use the titleLarge in the typography specified in KaigiTheme.

**Comment by risako070310** [comment]
Thanks to reply. I didn't know about the theme system of Compose. I'll look into it and try to implement it!!

**Comment by takahirom** [comment]
@risako070310 Are you OK? How's it going?

**Comment by risako070310** [comment]
@takahirom I still try it now, but I didn't have much time to apply. I push my commitment until tomorrow :(

**Comment by takahirom** [comment]
We can unassign you whenenever you want to give up. 👍 Please let us know if you want to.

**Comment by risako070310** [comment]
@takahirom I'm very sorry for the delay.
I created the pull request #621 , could you please confirm this for me?
