### ISSUE TITLE
Use Slot API pattern in KaigiTopAppBar for logo image 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#238]
**Idea Description**
We need to show the title instead of the logo in some screen.

About slot API pattern, Please refer to this.
https://github.com/DroidKaigi/conference-app-2022/issues/114

**Reference images and links**

```
fun KaigiTopAppBar(
    onNavigationIconClick: () -> Unit,
    modifier: Modifier = Modifier,
    elevation: Dp = 0.dp,
    title: (@Composable RowScope.() -> Unit), // ← new
    trailingIcons: (@Composable RowScope.() -> Unit)? = null,
```

**Comment by knyackiko** [comment]
I'll try this 🙋‍♀️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
