### ISSUE TITLE
Update Zipline

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#249]
**Idea Description**
Run zipline locally and see if it works when update.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/pull/58

**Comment by horie1024** [comment]
🙋

**Comment by horie1024** [comment]
The 0.92 release requires developers to explicitly opt out of signature checks.

> Breaking change: Require callers to explicitly opt out of signature checks. Pass
ManifestVerifier.Companion.NO_SIGNATURE_CHECKS to use ZiplineLoader without code signature
verification.

So we must pass the ManifestVerifier.Companion.NO_SIGNATURE_CHECKS when instantiating the ZiplineLoader.

**Comment by takahirom** [comment]
We are using it as an experimental approach. So it is OK 🙆

**Comment by horie1024** [comment]
Okay, I'll work on this 🙂

**Comment by takahirom** [comment]
Probably it is difficult to run. Please let me know if you need any help 🙏
