### ISSUE TITLE
Zipline is hanging when calling

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#250]
**Idea Description**

When we call it, the response does not come. When we use a local server, It works.

https://github.com/DroidKaigi/conference-app-2022/blob/9a5093652a62da0c96e7914be6702cee5c56f1b0/core-zipline/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/zipline/SessionsZipline.kt#L90

**Reference images and links**

**Comment by RyuNen344** [comment]
Thanks! assigned!

> Is it to get https://droidkaigi.github.io/conference-app-2022/manifest.zipline.json to load and work correctly with Zipline?

That's right! 💡

**Comment by kubode** [comment]
WIP

## Investigation

### Stack trace
```
Zipline modifier error
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 100 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by horie1024** [comment]
Hi. I am facing the same problem trying to solve https://github.com/DroidKaigi/conference-app-2022/issues/249.
I saw the same log too. And when I check, it seems that `prepareModifiers` is not executed.

**Comment by horie1024** [comment]
Question 🙋‍♂️

I am experiencing the same problem with the latest version 0.94 of zipline.

My task is to update the zipline version. So, can I submit a pull request first https://github.com/DroidKaigi/conference-app-2022/issues/249?

**Comment by horie1024** [comment]
By the way, the manifest download seemed to work fine.

**Comment by kubode** [comment]
My opinion is that this issue should be done after #249.
Because there are several breaking changes between Zipline 0.9.1 and 0.9.4.

**Comment by takahirom** [comment]
@horie1024 
Thanks for your opinions. Could you open PR first? 🙏

**Comment by takahirom** [comment]
The update is finished. 🙏

**Comment by kubode** [comment]
Thanks!
I will try to continue work on this issue.

**Comment by kubode** [comment]
@takahirom I have a question.

My understanding is that it can be fixed by changing the timing of closing the `zipline` instance in the `SessionsZipline`. (Investigation issue: https://github.com/kubode/conference-app-2022/issues/3#issuecomment-1246601669)

We can verify this using a breakpoint, but not on the actual look and feel of the Android application.
Because `JsScheduleModifier` is trying to modify a `TimetableItemId=1` item, but a `TimetableItemId=1` item is not present in the API response.

Is there any better way to verify this?

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
@kubode Thanks! Probably I forgot to delete it when removing callbackFlow{}.
I think you can check it by seeing the log.
https://github.com/DroidKaigi/conference-app-2022/blob/main/core-zipline/src/jsMain/kotlin/io/github/droidkaigi/confsched2022/zipline/JsScheduleModifier.kt#L16

**Comment by takahirom** [comment]
If you want to modify the data. I think we can modify the lunch description 😄

**Comment by kubode** [comment]
Thanks!
I know we can verify by checking `Hello JS world!` is logged.

> If you want to modify the data. I think we can modify the lunch description 😄 You can make a PR 🙏

OK, I will make that PR first for the verification of this issue.
