### ISSUE TITLE
Not to reuse Modifier instances more than necessary in SessionDetail.kt

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2022#254]
**Idea Description**
- I want to avoid passing the argument modifier of the composable fun to the child composable in the [SessionDetail.kt](https://github.com/DroidKaigi/conference-app-2022/blob/55948f565047505abb503899a77e40c2766f3ed5/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SessionDetail.kt) file.

- I want it like this↓.

```Kotlin
@Composable
fun SessionDetailSessionInfo(
    ...
    modifier: Modifier = Modifier,
) {
    Column(modifier = modifier) {  // pass modifier arguments to root composable
        Text(
            modifier = Modifier,  // not use modifier arguments
            ...
        )
        ...
   }
}
```

**Reference images and links**

**Comment by SSong-develop** [comment]
Can i get this issue?

**Comment by takahirom** [comment]
Thanks! Assigned 🙏
