### ISSUE TITLE
Add project icon

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#260]
![image](https://user-images.githubusercontent.com/1386930/188883996-d2e7cbaa-332a-456b-950d-350230d2266b.png)
All you have to do is put the image to `.idea/icon.png`
https://github.com/DroidKaigi/conference-app-2021/blob/main/.idea/icon.png

And we have an icon in app-android res folder.

**Comment by fumito-s** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
