### ISSUE TITLE
Insert margin between tab items

### ISSUE THREAD

**Issue by RyuNen344** [DroidKaigi/conference-app-2022#262]
insert between tab items 🙏 

| expects | now |
| --- | --- |
| ![margin](https://user-images.githubusercontent.com/32740480/188887405-811ee61c-c603-4031-b1b5-3d003f8c5f89.png) | ![Screenshot_20220907_221147](https://user-images.githubusercontent.com/32740480/188887578-82fd95d3-cbc0-48ba-9bf1-158630b968e3.png) |

[Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=448%3A2009)

**Comment by minibugdev** [comment]
🙋‍♂️

**Comment by RyuNen344** [comment]
Thanks！assinged！ 🙏
