### ISSUE TITLE
Make a common value for layout size

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#266]
**Idea Description**
There are values duplicated like timeTableColumnWidth = 192.dp and TimeTable.kt as roomHeaderWidth = 192.dp.
Can we make an object like this and make a common value?
Say, TimetableDefaults
https://github.com/android/nowinandroid/blob/900450eb059ce20d233ee611b4fd7fbaa0aa040e/core-designsystem/src/main/java/com/google/samples/apps/nowinandroid/core/designsystem/component/ToggleButton.kt#L102

**Reference images and links**

**Comment by wildstarzw** [comment]
🙋‍♂️

**Comment by t-yusaku** [comment]
@wildstarzw 
Thanks! Assigned 👍
