### ISSUE TITLE
Introduce Kotlin Explicit API mode to core-xxx modules

### ISSUE THREAD

**Issue by STAR-ZERO** [DroidKaigi/conference-app-2022#279]
**Idea Description**

Explicit visibility using `public` or `internal` or `private` allows you to control what expose outside the module. Kotlin default visibility is `public`, so you may expose things you don't want to be public. 

You can force explicit visibility using [Kotlin Explicit API mode](https://github.com/Kotlin/KEEP/blob/master/proposals/explicit-api-mode.md). It helps control visibility.

⚠️ Applying Explicit API mode requires changing many parts of existing code.

**Comment by takahirom** [comment]
Thank you for suggesting it. I'm using Explicit API mode in my company library project. It is useful when you should manage what you expose or not.
So, how about enabling it in core-xxx modules?

**Comment by STAR-ZERO** [comment]
I think it's good to apply it in the core modules.

I don't know the details of the convention plugin for this project, but it can be applied with the convention plugin.

**Comment by d1-morimoto** [comment]
Excuse me. This is an interesting idea.
How about writing ```explicitApiWarning()``` in "build.gradle.ktx" for each core-xxx module?
This has two advantages.

* Minimally rewrite
* Warning highlights make developers aware of "explicit mode"

**Comment by takahirom** [comment]
Thanks for your suggestion. Let me think it over 🙇

**Comment by d1-morimoto** [comment]
:bow:

**Comment by takahirom** [comment]
@d1-morimoto 
Sorry for keeping you waiting 🙇 
Let's use explicitApiWarning!
The reason is if you create the plugin or extension for it, it will probably provide the same API, and there are no pros.

**Comment by d1-morimoto** [comment]
Thank you for your decision:bow:
I'd like to make a PR to add "```explicitApiWarning()```" to  core-xxx module's "build.gradle.ktx" soon.
