### ISSUE TITLE
[Improve Timetable] Pinch in/out to change the scale of hours

### ISSUE THREAD

**Issue by t-yusaku** [DroidKaigi/conference-app-2022#290]
**Not sure if this issue is possible. Welcome to try it!**

**Idea Description**
We want to change the `Hours` scale on pinch in/out to show more sessions on the screen.
It means a UI like Google Calendar for Android (Day, 3days, Week). 

**Required**
- Max scale: Same as [the UI design](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App) (already implemented)
- Min scale: All sessions in **a room**  are displayed without scrolling
- Flexible the scale of 'Hours' and height of session items
- **Don't change** the scale of `Rooms`

**Reference images and links**
- No references.

**Comment by kafumi** [comment]
Although I might need some time to finish this task, could I try this one 🙋?

We should be able to use [`transformable`](https://developer.android.com/jetpack/compose/gestures#multitouch) modifier to detect zooming, but I guess we need some adjustment with dragging event handling (`PointerInputScope.detectDragGestures()`) for good zooming detection.

**Comment by takahirom** [comment]
I think so too! Thanks as always. Assigned.
