### ISSUE TITLE
Hoist URL handling to KaigiApp

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#296]
**Idea Description**

There are a lot of startActivity intent on screens to open web pages.
How about hosting the event and handling it in new `KaigiExternalNavigation`?

And we can also add navigateGitHub(xxx) for adding the special handling for the intent.

```
    kaigiAppScaffoldState: KaigiAppScaffoldState = rememberKaigiAppScaffoldState(),
    kaigiExternalNavigationController = rememberKaigiExternalNavigationController()
) {
aboutNavGraph(
...
  onLinkClick = kaigiExternalNavigationController::navigate
)
```

**Reference images and links**

**Comment by fornewid** [comment]
🙋‍♂️
