### ISSUE TITLE
Call reportFullyDrawn for performance

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#297]
**Idea Description**
It makes the app fast because it is used app optimization.

**Reference images and links**
https://github.com/android/nowinandroid/blob/c67812563be5a710ea8a57b0580f6436599df8a5/feature-foryou/src/main/java/com/google/samples/apps/nowinandroid/feature/foryou/ForYouScreen.kt#L153

**Comment by tasugi** [comment]
I'll try this!

**Comment by t-yusaku** [comment]
Thanks!! Assigned 😊
