### ISSUE TITLE
Introduce Detekt for Compose Lint

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#298]
**Idea Description**
I'm not familiar with it.
But I heard it has a useful rule.
Can we try it?

**Reference images and links**

**Comment by takahirom** [comment]
We want to use this 🙏 
https://github.com/DroidKaigi/conference-app-2022#configurable-build-logic

**Comment by iwata-n** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assinged 👍

**Comment by iwata-n** [comment]
Documentation is probably on this page.

https://detekt.dev/docs/introduction/compose/

**Comment by takahirom** [comment]
@iwata-n Have you ever used this?

**Comment by iwata-n** [comment]
Not yet!

**Comment by takahirom** [comment]
I was wondering if our app has a lot of issues with it 👀 
But let's try anyway!

**Comment by iwata-n** [comment]
Do you have any information?

**Comment by takahirom** [comment]
We are on the same page 😄

**Comment by iwata-n** [comment]
@takahirom 
Should I change the CI?

**Comment by takahirom** [comment]
If you can do it, it is the best.
But I leave it to you.👍

**Comment by iwata-n** [comment]
Thank you very much.
I found some issues with the lint results.
So, can I create another Issue after the merge?

**Comment by takahirom** [comment]
I think It's great.
Let's make it better step by step!
