### ISSUE TITLE
Make SmallTopAppBar TopAppBar

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#299]
**Idea Description**
SmallTopAppBar got deprecated. 

**Reference images and links**
https://developer.android.com/jetpack/androidx/releases/compose-material3?hl=en#1.0.0-beta02

**Comment by umsys** [comment]
I want to challenge myself with my first contribution. 🙋

**Comment by RyuNen344** [comment]
Thanks!assigned!🥳

**Comment by takahirom** [comment]
Thanks! Assigned! I'm rooting for you👍
