### ISSUE TITLE
Add easy test to announcement

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#300]
**Idea Description**

We would like to create a test like AboutScreenTest. The test is to check the announcement screens title exists.

**Reference images and links**

https://github.com/DroidKaigi/conference-app-2022/blob/main/feature-about/src/test/java/io/github/droidkaigi/confsched2022/feature/about/AboutScreenTest.kt

**Comment by Corvus400** [comment]
I would like to do this task.
