### ISSUE TITLE
Extract SessionDetailBottomAppBar Composable function

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#301]
**Idea Description**
SessionDetailScreen() is a little big.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SessionDetail.kt#L153

**Comment by ym223** [comment]
I'd like to do this issue :raising_hand:

**Comment by RyuNen344** [comment]
Thanks! Assigned! 🤟
