### ISSUE TITLE
KaigiScaffold and KaigiTopAppBar should be placed at io.github.droidkaigi.confsched2022.designsystem.components

### ISSUE THREAD

**Issue by yanzm** [DroidKaigi/conference-app-2022#310]
**Idea Description**

KaigiScaffold and KaigiTopAppBar is placed at `io.github.droidkaigi.confsched2022.designsystem.theme` package of core-designsystem module.
I think it should be at `io.github.droidkaigi.confsched2022.designsystem.components` package

**Reference images and links**

- https://github.com/DroidKaigi/conference-app-2022/blob/main/core-designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/designsystem/theme/KaigiScaffold.kt
- https://github.com/DroidKaigi/conference-app-2022/blob/main/core-designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/designsystem/theme/KaigiTopAppBar.kt

If the current package is intended, please close this issue.

**Comment by takahirom** [comment]
Definitely. Great catch! 👍

**Comment by yanzm** [comment]
please someone take this easy issue, I should use my time to prepare my session :-)

**Comment by takahirom** [comment]
Thanks! I'll assign it to you.
