### ISSUE TITLE
list mode selection should be keep through navigation

### ISSUE THREAD

**Issue by yanzm** [DroidKaigi/conference-app-2022#311]
**Describe the bug**

Session schedules can be shown in timetable mode or list mode.
This selection should be kept through navigation like moving to detail and back, but it will be reset to timetable mode after navigation.

**To Reproduce**

1. show timetable 
2. switch to list mode by clicking the calendar icon
3. move to session detail
4. click the back button
5. timetable is shown (should be list mode)

**Expected behavior**

Session schedules are shown in list mode after moving to detail and back.

**Screenshots**

https://user-images.githubusercontent.com/455504/189278274-a33bfcca-d037-49df-979f-da0da647dbfc.mp4

**Comment by takahirom** [comment]
We probably need to store the timetable or not in the NavBackStackEntry.
I think we have two options.
1. Use rememberSaveable
2. Use ViewModel

Since the value bring about many changes to the app, and it can affect other UiModels, it would be appropriate to place it in ViewModel.

**Comment by sudachi808** [comment]
I'll give it a try.🙋

**Comment by takahirom** [comment]
Thanks. Assigned!
