### ISSUE TITLE
The indicator for loading Contributors is located in the upper left corner

### ISSUE THREAD

**Issue by umsys** [DroidKaigi/conference-app-2022#312]
**Idea Description**
The indicator for loading Contributors is located in the upper left corner.
I think it would be better if it were placed in the center of the screen.

**Reference images and links**

|  Now | I think it would be better |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/45583423/189293154-63e72081-6eb2-4756-b34d-e25ccf11a2b4.png" width="320px"> | <img src="https://user-images.githubusercontent.com/45583423/189293445-c1edbac2-b973-42cd-ba08-63ce74fd1f51.png" width="320px"> |

**Comment by takahirom** [comment]
Good catch

**Comment by SSong-develop** [comment]
Can i get this issue?

**Comment by takahirom** [comment]
OK! Good luck!
