### ISSUE TITLE
Add `modifier = Modifier` parameter to all composable function in Search

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#323]
**Idea Description**
Please make it configurable.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/Search.kt
https://chris.banes.dev/always-provide-a-modifier/

**Comment by mikanIchinose** [comment]
✋🏻 
Can I challenge this work?

**Comment by RyuNen344** [comment]
Yes you can!! Thanks!! assigned!!

**Comment by mikanIchinose** [comment]
I have some questions.

### 1. Does the Function annotated `@Preview` need to have a `modifier` parameter?

In this case, the function is `SearchScreenPreview`

### 2. I think that the `modifier`'s position is the first. Is it OK?

ex.
```kotlin
private fun SearchTextField(
    modifier: Modifier = Modifier, // <- here
    searchWord: String,
    onSearchWordChange: (String) -> Unit
)
```

### 3. How many tasks are there?

I think there are 2 tasks for this issue.

1. Add `modifier` parameter to composable function signatures
2. Pass `modifier` to a suitable child composable function

Should I do both tasks or the first only?

**Comment by takahirom** [comment]
👀

**Comment by takahirom** [comment]
1. Sorry, I forgot the Preview functions. 😅 The function doesn't need to have a modifier parameter.
2. First optional parameter and before the content parameter is the best.
```
private fun Hoge(
    searchWord: String,
    onSearchWordChange: (String) -> Unit
    modifier: Modifier = Modifier, // I think here is the best. But I think it is not such an important rule. 
    optionalParameter: String? = null
    content: @Composable () -> Unit
)
```

https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#elements-accept-and-respect-a-modifier-parameter

3. Can you do both of them? Please pass it to the root composable function in it. 🙏

**Comment by mikanIchinose** [comment]
Thank you for your reply.
I'll do them.
