### ISSUE TITLE
Remove searchContentHeight

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#325]
**Idea Description**
A ordinary variable should not be used in Composable function if you want to recompose.
And I think we can do it with wrap content.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/Search.kt#L190

**Comment by hiesiea** [comment]
I'll try it!

**Comment by takahirom** [comment]
Thanks! Assigned 👍
