### ISSUE TITLE
Pass TimetableItem instead of passing many parameters.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#326]
**Idea Description**
I know there is a trade-off. 
But I want to create a method in TimetableItem for the UI logic in this project to standardize the logic.

https://github.com/DroidKaigi/conference-app-2022/blob/c3f9fa72e1e74aa6db5f3baad71d055f58e22cef/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SessionDetail.kt#L206
**Reference images and links**

**Comment by fumito-s** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned
