### ISSUE TITLE
Make navigation drawer scrollable

### ISSUE THREAD

**Issue by t-yusaku** [DroidKaigi/conference-app-2022#333]
**Idea Description**
- Title says everything.
- Because of not scrollable, it cannot be fully displayed when the screen size is not enough.
- This happens on devices like Pixel when it is portrait mode.

**Reference images and links**
![Screenshot_20220910-042952.png](https://user-images.githubusercontent.com/58973616/189429353-bd9b9da3-1823-41f7-ab98-ed7255000595.png)

**Comment by anzuchitakuro** [comment]
🙋

**Comment by t-yusaku** [comment]
@anzuchitakuro 
Thanks! Assigned 🙏
