### ISSUE TITLE
[API]I want to be able to display the supported languages for the session as well as the web version.

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2022#335]
**Idea Description**
On the web, it seems to be possible to display JP,EN or EN,JP, etc.
However, the API response structure used in the application only includes the speaker's first language, so it is not possible to support the same display as the web version.
To solve this, I think the structure should be languages(Array[String]) instead of language(String).

**Reference images and links**
![スクリーンショット 2022-09-10 7 21 50](https://user-images.githubusercontent.com/13657682/189453619-545da2c5-0b7d-4cf1-ad25-ea8df9410a82.png)
![スクリーンショット 2022-09-10 7 22 11](https://user-images.githubusercontent.com/13657682/189453622-49e980c0-53b5-46aa-a143-5b76b8799bdb.png)

**Comment by takahirom** [comment]
I'll have our staffs check it🙏

**Comment by takahirom** [comment]
The `interpretationTarget`  field will be added.

**Comment by RyuNen344** [comment]
`interpretationTarget` filed starts to work

if `interpretationTarget` be true, session has interpretation.
so app can display `not` speakers language.

**Comment by Corvus400** [comment]
I would like to do this task.

**Comment by RyuNen344** [comment]
Thanks!!! assigned!!!!
