### ISSUE TITLE
Make progress indicator center

### ISSUE THREAD

**Issue by yoshimuratakuma0** [DroidKaigi/conference-app-2022#338]
Idea Description
- it's the same as title.

Reference images and links
![image](https://user-images.githubusercontent.com/88303689/189471644-409db523-7226-4d6f-99b0-70a5a7a51c86.png)

**Comment by yoshimuratakuma0** [comment]
✋

**Comment by t-yusaku** [comment]
@yoshimuratakuma0 
Thanks for your report 👍 
But I think this is same as  #312  #322 
So, could you please check if there is any problem with the latest version. 🙏 
If there is no problem, I will close the issue.

**Comment by yoshimuratakuma0** [comment]
@t-yusaku 
Exactly.
I'm sorry for checking it beforehand:bow:
Thank you so much.

**Comment by t-yusaku** [comment]
@yoshimuratakuma0 
No problem! Thanks for checking 🙏 
We are looking forward to the next time if you have 👍
