### ISSUE TITLE
Add padding to `Contributors` icon

### ISSUE THREAD

**Issue by t-yusaku** [DroidKaigi/conference-app-2022#342]
**Idea Description**
- According to the app design, there is a blank between the contributor's icons

**Reference images and links**
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App
![image](https://user-images.githubusercontent.com/58973616/189475922-6d75f455-857b-4485-b0da-f750432e5024.png)

**Comment by iiinaiii** [comment]
I'd like to try this issue 🙋

**Comment by t-yusaku** [comment]
@iiinaiii 
Thanks!! Assigned 👍
