### ISSUE TITLE
The session's titles become too small when they shrink.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#344]
**Idea Description**
We can define minimum text size. I think we can use 4 or 8 or 12 sp. Can you prototype and decide it?
I think we can calculate the size by (16sp / verticalScale) or 16sp * verticalScale and change the scale.
https://github.com/DroidKaigi/conference-app-2022/blob/f799ad158e73db9d28db579d2b4c7b9d489a6e92/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/TimetableItem.kt#L41

**Reference images and links**
[device-2022-09-10-203636.webm](https://user-images.githubusercontent.com/1386930/189481545-2b56528a-7501-4e27-8d09-9fa2f17d8111.webm)

**Comment by t-yusaku** [comment]
My opinion is here https://github.com/DroidKaigi/conference-app-2022/pull/320#discussion_r967192630
I think that keeping default text size is better for visibility.  Instead, omit text that does not fit in the session item. 🤔 
But it is just in my opinion. So, I leave the decision to @takahirom and the assignee of this issue. 🙏

**Comment by takahirom** [comment]
I think this way. But I think the default size can be the `not readable size` too early. So I would like to use `readable size`.
default size > readable size > too small size > not readable size

**Comment by t-yusaku** [comment]
> But I think the default size can be the not displayed too early.

That's make sense. I agree with you. 
It is better way to define and use the readable size than only the default size.  👍

**Comment by warahiko** [comment]
I would like to do this task 🙋
In my understanding, we should use variable text size (but it has minimum value) because if we keep default size the text will be omitted early. 
Is that ok?

**Comment by t-yusaku** [comment]
Yes, you're right.  
Thank you for raising your hand! 👍

**Comment by takahirom** [comment]
I thought we could calculate the minimum density for 8 sp in normal density. But is it difficult?

**Comment by takahirom** [comment]
For example
density = maxOf((8sp / 14sp)  * density, density)

**Comment by warahiko** [comment]
ah, I was wrong...
We should change the density parameter, not the text size, I see.
Yes, I think we can calculate a density that makes the text size of the title 8.sp.
