### ISSUE TITLE
Reduce 1 minute when calculate timetable item height to separate each sessions.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#345]
**Idea Description**
We want to make a space here so. When calculating session height, I would like to use `minute - 1` height.
![image](https://user-images.githubusercontent.com/1386930/189482383-9227c45d-5691-46fe-b629-a2db5fd9f29e.png)

**Reference images and links**

https://github.com/DroidKaigi/conference-app-2022/blob/60ab6c88adf362103600a05d8b2a386d60a51f53/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/Timetable.kt#L252

**Comment by rmakiyama** [comment]
🙋🏻‍♂️I'll try it!

**Comment by t-yusaku** [comment]
Assigned!! Thanks 👍
