### ISSUE TITLE
Move session detail date to strings.xml's format

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#347]
**Idea Description**
We have English speakers at the conference. So we have to show English. So please adapt by strings.xml resource.

**Reference images and links**
strings.xml format
https://developer.android.com/guide/topics/resources/string-resource#formatting-strings

https://github.com/DroidKaigi/conference-app-2022/blob/b596f1baa82f345d1645a94b6c9f8f5f685b176f/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SessionDetail.kt#L312

**Comment by att55** [comment]
I'd like to do this task 🙋🏼

**Comment by takahirom** [comment]
Thanks! Assigned!
