### ISSUE TITLE
Apply the english version for the about description

### ISSUE THREAD

**Issue by t-yusaku** [DroidKaigi/conference-app-2022#349]
**Idea Description**
- Title says everything
- Use same text as Web https://droidkaigi.jp/2022/en/
> DroidKaigi is a conference tailored for Android developers.
It's scheduled to take place on the 5 to 7 of October 2022.

**Reference images and links**
<img src="https://user-images.githubusercontent.com/58973616/189484215-d460f6f1-ab63-43f0-9c06-2c1ccfa9aab1.png" width="480" />

**Comment by att55** [comment]
I'd like to do this task 🙋

**Comment by takahirom** [comment]
Thanks! Assigned!🙏
