### ISSUE TITLE
Screen flickering when transitioning between screens

### ISSUE THREAD

**Issue by rmakiyama** [DroidKaigi/conference-app-2022#355]
**Idea Description**

Currently, screen flickering when transitioning between screens
It's hard to tell if the device is set to dark mode, but it's clearly happening if it's not in dark mode.

The cause is that the screen transition is a CrossFade animation, so the background color of MainActivity is shown.

**Reference images and links**

> **Note** Not in dark mode.

https://user-images.githubusercontent.com/7961496/189487297-d614c8f5-6739-4734-b0ae-b99ba1485434.mp4

**Comment by rmakiyama** [comment]
May I work on this issue? 👀

**Comment by takahirom** [comment]
OK!🙆 I thought it is default animation of navigation compose. 
I'm looking forward to seeing your implementation👀

**Comment by rmakiyama** [comment]
Thanks😄

> I thought it is default animation of navigation compose.

Yes, and I think the default animation should not be changed.
I plan to try changing the theme.xml settings.
