### ISSUE TITLE
Session speakers are not shown

### ISSUE THREAD

**Issue by yukilabo** [DroidKaigi/conference-app-2022#365]
**Describe the bug**
Session speakers are not shown.

It looks like SessionDao is not storing session speakers in DB.
https://github.com/DroidKaigi/conference-app-2022/blob/main/core-data/src/commonMain/kotlin/io/github/droidkaigi/confsched2022/data/sessions/SessionsDao.kt#L60-L62

**To Reproduce**
1. Go to any session detail screen
2. Always speakers are not shown

**Expected behavior**
Speakers are shown.

**Screenshots**
<img src="https://user-images.githubusercontent.com/3139391/189498904-f1ad5ccc-8faa-4dc0-9670-55a7f7a25516.jpg" width="300" />

**Comment by Corvus400** [comment]
I would like to do this task.

**Comment by takahirom** [comment]
Thanks as always 🙏
