### ISSUE TITLE
Align SessionItem to the line

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#368]
The app
<img width="51" alt="image" src="https://user-images.githubusercontent.com/1386930/189521861-a6173da2-739a-4ad9-80ba-0e958b4ab108.png">
Design
<img width="976" alt="image" src="https://user-images.githubusercontent.com/1386930/189521881-f06b638a-e733-4f61-8152-38c959c3f08f.png">

**Comment by ochim** [comment]
🙋‍♀️ I try

**Comment by t-yusaku** [comment]
Thanks! Assigned 👍

**Comment by ochim** [comment]
OK?
![Screenshot_20220912_003826](https://user-images.githubusercontent.com/7196624/189536752-7d504095-ca55-4a95-b5cf-2dcffb6a7681.png)

**Comment by takahirom** [comment]
I can see a little difference. Let me reopen this issue 🙏 
current
<img width="218" alt="image" src="https://user-images.githubusercontent.com/1386930/189559484-e855d9ac-badd-4209-a339-6a439130181c.png">
design
<img width="155" alt="image" src="https://user-images.githubusercontent.com/1386930/189559492-edb17f9d-f822-45d2-9416-067ea0139271.png">

**Comment by ochim** [comment]
Sorry,  I retry

**Comment by ochim** [comment]
What is the width of the line ?
dynamic or static ?

**Comment by takahirom** [comment]
Thanks! The line is 1dp.
https://github.com/DroidKaigi/conference-app-2022/blob/b94d518a14008073a99d27af54f63da856e1e6d5/feature-sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/Timetable.kt#L614
Your screenshot seems there is space with it 👀

**Comment by ochim** [comment]
![Screenshot_20220912_151915](https://user-images.githubusercontent.com/7196624/189588388-3ad39f6c-5475-4d65-8315-f416e5daa85f.png)
OK?

**Comment by ochim** [comment]
@takahirom please check

**Comment by takahirom** [comment]
Looks great 👍 Thanks!
