### ISSUE TITLE
Apply textStyle by CompositionLocal for KaigiScaffold title

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#372]
**Idea Description**

     KaigiScaffold(
         topBar = {
             KaigiTopAppBar(
                 showNavigationIcon = showNavigationIcon,
                 onNavigationIconClick = onNavigationIconClick,
                 title = {
                     Text(
                         text = stringResource(id = R.string.setting_title),
                         style = MaterialTheme.typography.titleLarge, // ←←
                     )
                 },
             )
         }

**Reference images and links**

**Comment by tarumzu** [comment]
I'd love to try this issue!

**Comment by takahirom** [comment]
Thanks! Assigned!🙏
