### ISSUE TITLE
Use round ripple to about icons

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#373]
**Idea Description**
I'd like to show it like a navigaton icon

**Reference images and links**
![Screenshot_20220911-231931.png](https://user-images.githubusercontent.com/1386930/189532486-f4bab9bc-0b92-4144-9962-9b2d109e143e.png)

**Comment by iiinaiii** [comment]
I would like to try this issue 🙋

**Comment by takahirom** [comment]
@iiinaiii Sorry to keep you waiting. Thanks! Assigned 👍
