### ISSUE TITLE
[iOS] Create SessionDetail UI

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#380]
**Idea Description**

- Please implement SessionDetail UI to `SessionView`.
  - Preview only is okey.
  - Some actions from this view aren't included in this issue.

**Reference images and links**
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=21%3A583
<img width="198" alt="スクリーンショット 2022-09-12 1 28 14" src="https://user-images.githubusercontent.com/30540303/189538525-12b29b61-d48a-48ea-b4c6-72bd73e6eedd.png">

**Comment by surajsau** [comment]
I would like to attempt this 🤚 🙇‍♂️

**Comment by sobaya-0141** [comment]
Thanks! Assigned :+1:
