### ISSUE TITLE
[iOS] Create Contributors UI

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#381]
**Idea Description**

- Please implement Contributors UI to `ContributorView`.
  - Preview only is okey.
  - Reflect api response isn't included in this issue.

**Reference images and links**
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=372%3A2616
<img width="225" alt="スクリーンショット 2022-09-12 1 30 39" src="https://user-images.githubusercontent.com/30540303/189538676-469a20ed-f50a-43e6-96cf-27717d1082dd.png">

**Comment by sudachi808** [comment]
i'll give it a try 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
