### ISSUE TITLE
[iOS] Fix AboutView content padding

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#382]
**Idea Description**

- Currently, `AboutView` 's content paddings (for example, description padding) are not correct.
  - ~`What is DroidKaigi?` Label~
  - ~Description~
  - Tiles (Access, Staffs, Privacy Policy)

**Reference images and links**
Current|Expected
--|--
<img src="https://user-images.githubusercontent.com/30540303/189538853-6842a555-950f-4d01-b2d8-336199b6dc5a.png" width="300px">|<img src="https://user-images.githubusercontent.com/30540303/189538813-e8bb7104-0a3a-4053-8319-c05f43471b5c.png" width="300px">

**Comment by onakama** [comment]
I would like to challenge this.

**Comment by RyuNen344** [comment]
💪💪💪💪
assigned!!!

**Comment by ry-itto** [comment]
I'm sorry, I wrote some parts that didn't need to be fixed due to my misunderstanding 🙇🏼 

Here's what needs fixing:
- Tiles (Access, Staffs, Privacy Policy)
