### ISSUE TITLE
[iOS] Remove unnecessary spacing in `TimetableView`

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#383]
**Idea Description**

- Currently, unnecessary spacing is showed in `TimetableView`. Please remove it.

**Reference images and links**

<img width="484" alt="スクリーンショット 2022-09-12 1 35 36" src="https://user-images.githubusercontent.com/30540303/189538994-b555d04e-ad45-4f74-80e1-8ece38652439.png">

**Comment by takagisou** [comment]
I'll try it. 🙋‍♀️

**Comment by takahirom** [comment]
Thanks! Assigned!
