### ISSUE TITLE
Per-app language preferences backport to below sdk 32

### ISSUE THREAD

**Issue by RyuNen344** [DroidKaigi/conference-app-2022#385]
**Idea Description**

https://github.com/DroidKaigi/conference-app-2022/issues/192

per app language support was introduced above PR

android provides backport for Android 12 and lower
https://developer.android.com/guide/topics/resources/app-languages#android12-impl

### block
- [x] https://github.com/DroidKaigi/conference-app-2022/issues/192

**Comment by nashcft** [comment]
🙋

**Comment by RyuNen344** [comment]
Thanks! Assigned!!
