### ISSUE TITLE
Change KaigiTopAppBar color 

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#405]
**Idea Description**
app
<img width="470" alt="image" src="https://user-images.githubusercontent.com/1386930/189853765-84a962d4-96d6-46c4-9cbd-b0fc4a12acd5.png">
design
<img width="242" alt="image" src="https://user-images.githubusercontent.com/1386930/189853968-9ec89af1-3494-4e67-81b2-09a8ffb49da2.png">

**Reference images and links**

**Comment by itochan** [comment]
I want to try.
Please assign to me.

**Comment by att55** [comment]
I'd like to do this 🙋🏼

**Comment by takahirom** [comment]
Thanks! Assigned 👍
