### ISSUE TITLE
Try Twitter Compose rule

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#407]
**Idea Description**
Our repository can be a playground for this 👍 
This issue is just a trial, so it is possible that it may not make it to the merge into the main branch.

**Reference images and links**
https://github.com/twitter/compose-rules

**Comment by takahirom** [comment]
Can we use detectRule?

https://github.com/DroidKaigi/conference-app-2022/blob/main/gradle/plugins/src/main/kotlin/io/github/droidkaigi/confsched2022/primitive/DetektPlugin.kt
We can check it by `./gradlew composeLint`

**Comment by kwmt** [comment]
I'm interested in the issue. Let me try!

**Comment by sobaya-0141** [comment]
Thanks! Assigned :+1:
