### ISSUE TITLE
[edge-to-edge] Draw content behind the navigation bar

### ISSUE THREAD

**Issue by Mori-Atsushi** [DroidKaigi/conference-app-2022#408]
**Idea Description**
It is recommended to draw content behind the navigation bar in Android 10 or later.
This allows content to be drawn from edge-to-edge of the screen, enhancing the immersive experience of the application.

**Reference images and links**
https://developer.android.com/develop/ui/views/layout/edge-to-edge

**Comment by Mori-Atsushi** [comment]
I can tackle the first screen 🙋‍♂

**Comment by takahirom** [comment]
Thanks as always! Assigned 🙏
