### ISSUE TITLE
Show keyboard input when you open search screen

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#415]
**Idea Description**
The title says everything

**Reference images and links**
<img width="383" alt="image" src="https://user-images.githubusercontent.com/1386930/189879120-eefbe9dd-3f05-4536-aeaf-6f7ec997cf04.png">

**Comment by kawagh** [comment]
:raising_hand:

**Comment by takahirom** [comment]
Thanks! Assigned 👍
