### ISSUE TITLE
[iOS] Incorrect navigation style in iPad

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#423]
**Idea Description**

- In iPad, tabView ui is incorrect.
- `navigationStyle(.stack)` may be useful

**Reference images and links**
Current appearance 1 | Current appearance 2
--|--
<img width="680" alt="スクリーンショット 2022-09-13 23 00 49" src="https://user-images.githubusercontent.com/30540303/189921442-dcb01331-449c-4e28-ba1e-e3645d55d1ab.png">|<img width="680" alt="スクリーンショット 2022-09-13 23 00 56" src="https://user-images.githubusercontent.com/30540303/189921468-f0b3232d-e31b-4c94-80c7-99fd8939de8d.png">

**Comment by yamanetaisei** [comment]
I would like to try this.

**Comment by ry-itto** [comment]
@yamanetaisei 
Thanks! assigned 👍🏼
