### ISSUE TITLE
[iOS] Add app-version to `AboutView`

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#427]
**Idea Description**

- Add app-version to `AboutView`

**Reference images and links**
<img width="267" alt="スクリーンショット 2022-09-14 1 42 30" src="https://user-images.githubusercontent.com/30540303/189959162-3452af22-5ab4-42d4-8d22-7e0e28cf46f0.png">

**Comment by coffmark** [comment]
🙋‍♂️

**Comment by sobaya-0141** [comment]
Thanks! Assigned :+1:
