### ISSUE TITLE
[iOS] Open DroidKaigi official information links

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#428]
**Idea Description**
- Please implement open link about DroidKaigi official information
  - Medium
  - YouTube
  - Twitter

**Reference images and links**
<img width="255" alt="スクリーンショット 2022-09-14 1 46 14" src="https://user-images.githubusercontent.com/30540303/189959805-115c6648-195a-4a88-947d-8f0f69e9383d.png">

**Comment by NakaokaRei** [comment]
I'd like to try this issue!

**Comment by ry-itto** [comment]
@NakaokaRei 
Thanks! Assigned 👍🏼 
(Already created PR .. 👀 )

**Comment by NakaokaRei** [comment]
@ry-itto 
Sorry, I created PR before I was assigned🙇

**Comment by ry-itto** [comment]
No problem! Great work 👍 :+1
