### ISSUE TITLE
[iOS] Open License Page from `AboutView`

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#429]
**Idea Description**

- Implement license page ([LicensePlist](https://github.com/mono0926/LicensePlist) way is okey)
- Open license page from `AboutView`

**Reference images and links**

**Comment by touyou** [comment]
🙋‍♂️

**Comment by RyuNen344** [comment]
Thanks!! Assigned!! 💪💪💪💪
