### ISSUE TITLE
[iOS] Create StaffView

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#430]
**Idea Description**

- Create StaffFeature target
- Create StaffView in StaffFeature target
  - UI only is okey 👍🏼 
  - implement StaffView UI with ContributorView design once.

**Reference images and links**
<img width="268" alt="スクリーンショット 2022-09-14 1 59 48" src="https://user-images.githubusercontent.com/30540303/189962292-798c9b9f-a8a4-4f8c-8d3f-c9ed6dfb2907.png">

**Comment by coffmark** [comment]
✋

**Comment by RyuNen344** [comment]
Thanks!!! Assigned!!! 💪💪💪💪💪
