### ISSUE TITLE
[iOS] Add Online roomColor

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#432]
**Idea Description**

- Currently, roomColor for online session is missing. So please add online roomColor to `TimetableRoom.swift`

**Reference images and links**
<img width="390" alt="スクリーンショット 2022-09-14 2 02 19" src="https://user-images.githubusercontent.com/30540303/189962780-9665c2c3-1220-4bde-8bcc-866d821da1e3.png">

**Comment by Take111** [comment]
I'd like to try this issue!

**Comment by sobaya-0141** [comment]
Thanks! Assigned :+1:
