### ISSUE TITLE
[iOS] Shrink timetable day selection

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#433]
**Idea Description**

- In design, day selection items are shrunk when timetable scrolled.
- Please add interactive animation about that.

**Reference images and links**
<img width="730" alt="スクリーンショット 2022-09-14 2 06 23" src="https://user-images.githubusercontent.com/30540303/189963592-60d8c57d-94cf-465d-98c8-238e92379680.png">

**Comment by sudachi808** [comment]
🙋

**Comment by ry-itto** [comment]
@sudachi808 
Thanks! Assigned 👍🏼
