### ISSUE TITLE
Refine preview test

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#445]
**Idea Description**
The author of PR https://github.com/DroidKaigi/conference-app-2022/pull/97 is busy. So can you take over the PR?

We can do it by creating pr to `add_preview_test` branch

The remaining tasks

* Fix build
https://github.com/DroidKaigi/conference-app-2022/actions/runs/3049373353/jobs/4915373282
https://github.com/DroidKaigi/conference-app-2022/actions/runs/3049373357/jobs/4915373178

* Make a plugin
https://github.com/DroidKaigi/conference-app-2022/pull/97#discussion_r966599043

**Reference images and links**

**Comment by RyuNen344** [comment]
Thanks!!! Assigned!!

**Comment by aqua-ix** [comment]
I opened PR.
