### ISSUE TITLE
[Android] Room tag color doesn't match the room color

### ISSUE THREAD

**Issue by surajsau** [DroidKaigi/conference-app-2022#447]
**Describe the bug**
In `SessionDetails` the Room tag color doesn't match the corresponding room's color

**Expected behavior**
I think it would be better to set the correct room color as per [Figma](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=448%3A2009).

**Screenshots**
<table>
<tr>
<td>
<img width="300" alt="スクリーンショット 2022-09-14 14 31 23" src="https://user-images.githubusercontent.com/5493586/190067870-017e17a0-f7d3-4314-b326-f9f0e1710e02.png">
</td>
<td>
<img width="300" alt="スクリーンショット 2022-09-14 14 32 05" src="https://user-images.githubusercontent.com/5493586/190067876-64b99c54-37ae-43d8-bd8d-e95fe31415d9.png">
</td>
</tr>
<tr>
<td>
<img width="300" alt="スクリーンショット 2022-09-14 14 31 54" src="https://user-images.githubusercontent.com/5493586/190067880-17271e47-c448-4921-82d4-100930661994.png">
</td>
<td>
<img width="300" alt="スクリーンショット 2022-09-14 14 31 45" src="https://user-images.githubusercontent.com/5493586/190067883-95ecb3d0-3773-49e7-97a9-799a3cfbf47f.png">
</td>
<td>
<img width="300" alt="スクリーンショット 2022-09-14 14 31 36" src="https://user-images.githubusercontent.com/5493586/190067887-0aac324c-fc0d-4229-80da-5ef12459021c.png">
</td>
</tr>
</table>

**Comment by takahirom** [comment]
Thanks!

**Comment by surajsau** [comment]
Closing issue since it is merged 👍
