### ISSUE TITLE
[edge-to-edge] Apply edge to edge into contributors page

### ISSUE THREAD

**Issue by chigichan24** [DroidKaigi/conference-app-2022#458]
**Idea Description**
On the #408, just applied the edge to edge into the about page. But we should apply an edge to edge all other pages too.
In this issue, we focus on the contributors page.

**Reference images and links**
https://developer.android.com/develop/ui/views/layout/edge-to-edge
https://github.com/DroidKaigi/conference-app-2022/issues/408

**Comment by chigichan24** [comment]
I'll try to this issue~ 🙋‍♂️

**Comment by RyuNen344** [comment]
Thanks for your suggestion!!

assigned!!!
