### ISSUE TITLE
[edge-to-edge] Apply edge to edge into SessionsScreen

### ISSUE THREAD

**Issue by Mori-Atsushi** [DroidKaigi/conference-app-2022#459]
**Idea Description**
* I think SessionsScreen also prefers to render content behind the navigation bar.
* We also need to fix the issue that the navigation bar and buttons overlap in landscape.

portrait|landscape
:--:|:--:
![Screenshot_20220914_214302](https://user-images.githubusercontent.com/13435109/190156933-3c54c004-fdaf-4d09-8895-965f871721b0.png)|![Screenshot_20220914_214335](https://user-images.githubusercontent.com/13435109/190156939-1889bc5a-1840-4af0-9fcf-4ad072fa96ec.png)

**Reference images and links**
https://developer.android.com/develop/ui/views/layout/edge-to-edge
https://github.com/DroidKaigi/conference-app-2022/issues/408

**Comment by takahirom** [comment]
Thanks!
