### ISSUE TITLE
[Layout] An unnecessary gap between the drawer and the content in landscape

### ISSUE THREAD

**Issue by Mori-Atsushi** [DroidKaigi/conference-app-2022#465]
**Describe the bug**
* There will be an unnecessary gap between the drawer and the content as much as the width of the navigation bar.
* Occurs under the following conditions:
  * 3 buttons mode
  * A navigation bar appears on the left
  * large screen device (galaxy z flip3  etc.)

**Expected behavior**
Remove unnecessary gaps.

**Screenshots**
1|2
:--:|:--:
![Screenshot_20220914_235408](https://user-images.githubusercontent.com/13435109/190190828-e7903e79-d715-4033-a8ab-0c24e6f8e53e.png)|![Screenshot_20220914_235400](https://user-images.githubusercontent.com/13435109/190190852-1895c3c6-1bb8-4b27-a93e-de6b57fc9e85.png)

**Comment by Mori-Atsushi** [comment]
Maybe i can fix it

**Comment by takahirom** [comment]
It's looks natural. But It's padding is probably for navigation bar, right?
Good catch!

**Comment by takahirom** [comment]
Thanks! Assigned!
