### ISSUE TITLE
[iOS] Toggle TimetableSheetView and TimetableListView

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#470]
**Idea Description**

- Currently, TimetableView shows TimetableSheetView only. Please toggle those with button.

**Reference images and links**

![スクリーンショット 2022-09-15 12 44 26](https://user-images.githubusercontent.com/30540303/190309236-9e556114-436a-47cf-ae9d-0e8b5c971523.png)

**Comment by Tomoya113** [comment]
🤚

**Comment by ry-itto** [comment]
@Tomoya113 
Thanks! Assigned 👍🏼

**Comment by ry-itto** [comment]
@Tomoya113 
In https://github.com/DroidKaigi/conference-app-2022/pull/561, a contributor have done this issue. So I close this issue 🙏🏼 
Looking forward to other contributions!

**Comment by woxtu** [comment]
@Tomoya113 Sorry, I missed this issue.

**Comment by Tomoya113** [comment]
@woxtu No problem!
