### ISSUE TITLE
Build fail `multiplatform_strings.xml: Resource and asset merger: Duplicate resources` on Windows or Linux

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#473]
**Describe the bug**
The title says everything. 

**To Reproduce**
On Windows or Linux

**Expected behavior**
You can build DroidKaigi app.

**Screenshots**
https://twitter.com/usuiat/status/1570250608724287488
![image](https://user-images.githubusercontent.com/1386930/190314246-d09cb1fc-04a4-4a75-82b6-7b4ebdc41c70.png)

**Comment by takahirom** [comment]
It occurs in the test. Is this cache problem?
> Task :core-model:generateDebugResValues FROM-CACHE
> Task :core-model:generateDebugResources UP-TO-DATE
ERROR:[string/about_top_app_bar_title] /home/runner/work/conference-app-2022/conference-app-2022/core-model/build/generated/moko/androidMain/res/values/multiplatform_strings.xml [string/about_top_app_bar_title] /home/runner/work/conference-app-2022/conference-app-2022/core-model/build/generated/moko/androidMain/res/values/multiplatform_strings.xml: Resource and asset merger: Duplicate resources

**Comment by takahirom** [comment]
There is not cache tasks 🤔 
https://github.com/DroidKaigi/conference-app-2022/blob/main/.github/workflows/UpdateScreenshots.yml

**Comment by takahirom** [comment]
I thought it is only a CI problem. But the contributors using windows can't build it.
Probably we should revert Moko-Resource for Windows users.

**Comment by takahirom** [comment]
@kittinunf 
I should apologize. I guess we should revert it to Windows users. What do you think of it?

**Comment by rikuyu** [comment]
This also happens in my environment.

【My Environment】
・OS Windows
・Android Studio Electric Eel | 2022.1.1 Canary 10
・Gradle 7.5.1
・AGP 7.3.0-rc01

**Comment by usuiat** [comment]
Thank you for creating an issue.
I also use Windows.

- Windows 11 Home
    - Version 21H2
    - OS Build 22000.856
- AMD Ryzen 7 5800H
- Android Studio Electric Eel 2022.1.1 Canary 10

**Comment by usuiat** [comment]
I tried the following.

```
gradlew app-android:assembleDevDebug  --no-build-cache
```

The result was same. 

```
> Task :core-model:packageDebugResources FAILED
ERROR:[string/about_top_app_bar_title] C:\src\repo\DroidKaigi-original\conference-app-2022\core-model\build\generated\moko\androidMain\res\values\multiplatform_strings.xml [string/about_top_app_bar_title] C:\src\repo\DroidKaigi-original\conference-app-2022\core-model\build\generated\moko\androidMain\res\values\multiplatform_strings.xml: Resource and asset merger: Duplicate resources
(Many simillar errors occurred.)
```

**Comment by takahirom** [comment]
@usuiat Can you try the check-moko-resource branch?

**Comment by takahirom** [comment]
https://github.com/DroidKaigi/conference-app-2022/pull/480/files

**Comment by kittinunf** [comment]
Let me see what I can do for this.

**Comment by usuiat** [comment]
@takahirom Build successful on the check-moko-resource branch.

**Comment by takahirom** [comment]
@usuiat I merged that. Let me know if you need any help!

**Comment by usuiat** [comment]
Thank you for the quick support! Now I can build the main branch.
