### ISSUE TITLE
Open floor map from session detail ▲

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#485]
**Idea Description**
Now It makes the app crash.
**Reference images and links**
<img width="148" alt="image" src="https://user-images.githubusercontent.com/1386930/190391510-95a1a424-d8ce-48cc-8c00-9f51c2534152.png">

**Comment by att55** [comment]
I'd like to try this issue. 🙋🏼

**Comment by takahirom** [comment]
Thanks!

**Comment by takahirom** [comment]
@att55 Are you OK?

**Comment by takahirom** [comment]
@att55 This issue needs to be made by 9/23, can you take the time?

**Comment by takahirom** [comment]
@att55 Since I can't seem to reach you, please let me remove your assignment once.

**Comment by takathemax** [comment]
I'd like to try this issue if you don't mind.

**Comment by takahirom** [comment]
@takathemax Thanks a lot! We need this feature 🙏

**Comment by att55** [comment]
@takahirom I'm really sorry for my late reply. 🙇🏼 🙇🏼 
And thank you for your reassigning. 🙇🏼
