### ISSUE TITLE
Apply font to time and room on session list

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#486]
**Idea Description**
The title says everything

**Reference images and links**
<img width="599" alt="image" src="https://user-images.githubusercontent.com/1386930/190392012-f7430e94-569f-4ac0-a3f8-739b9c210dcf.png">

![image](https://user-images.githubusercontent.com/1386930/190391742-9b869ea9-c65c-4a2c-85bf-e865c0ab0e6d.png)
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by misuzz** [comment]
I'd like to try this issue. 🙋🏼

**Comment by takahirom** [comment]
Thanks! Assigned!🙏
