### ISSUE TITLE
Speakers associated with session ID:364756 are not displayed

### ISSUE THREAD

**Issue by Corvus400** [DroidKaigi/conference-app-2022#488]
**Describe the bug**
As the title says.

**To Reproduce**
1. find `マンガアプリのメモリ改善とメモリ解析方法` from the session
2. tap `マンガアプリのメモリ改善とメモリ解析方法`
3. check to see if the speaker appears
4. Speaker icons and names are not displayed.

**Expected behavior**
The icon and name of the speaker are displayed.

**Screenshots**
![Screenshot_20220915_220432](https://user-images.githubusercontent.com/13657682/190411805-519dd99e-d575-4ccb-bdc0-8e260d2cfb09.png)

**Comment by Corvus400** [comment]
I will investigate this bug as I was in charge of the DB task.
#388

**Comment by takahirom** [comment]
I didn't notice that. This must be problem. Great catch 🙏
