### ISSUE TITLE
Fix day tabs's font

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#492]
**Idea Description**

**Reference images and links**
app
![image](https://user-images.githubusercontent.com/1386930/190520552-c70ef9fe-6496-485e-ba30-e563039daafe.png)

design
<img width="932" alt="image" src="https://user-images.githubusercontent.com/1386930/190520620-e4d16cc2-92f8-4925-b44a-11ff1cc7d2b1.png">
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by shxun6934** [comment]
I'd like to try this issue. 🙋🏼

**Comment by takahirom** [comment]
Thanks! Assinged
