### ISSUE TITLE
Sticky time scroll in session list

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#493]
**Idea Description**
Can we scroll sticky?
I would like to scroll in session list not in timetable.

**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/190520803-c9e69ff1-5100-4110-97d0-66990a041e37.png)

https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by YagiRyu** [comment]
I'd like to try this issue. 🖐

**Comment by YagiRyu** [comment]
Sorry...
I give up this issue.🥲

**Comment by takahirom** [comment]
@YagiRyu 
Don't worry. Nice try! Thank you for your efforts!

**Comment by ryu38** [comment]
I'd like to try it! 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
