### ISSUE TITLE
Fix session detail title font

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#494]
**Idea Description**

**Reference images and links**
app
![image](https://user-images.githubusercontent.com/1386930/190520988-7e9b4326-2ea2-45f0-9d72-84b8368a13ee.png)
design
<img width="720" alt="image" src="https://user-images.githubusercontent.com/1386930/190521240-c6b147e8-48a8-4930-89f0-91a876e4e67a.png">
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by tomorrowkey** [comment]
I'd like to fix 😉

**Comment by sobaya-0141** [comment]
Thanks! Assigned :+1:
