### ISSUE TITLE
Add padding to session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#495]
**Idea Description**
Please add padding 16dp here.

**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/190521342-882d65ce-ac71-4eef-9010-f0c6c25c37c9.png)

**Comment by misuzz** [comment]
I'd like to try this one.

**Comment by takahirom** [comment]
Thanks! Assigned 👍
