### ISSUE TITLE
Separate CI workflow to post preview test comment

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#497]
**Idea Description**
Now, if you don't fork repository and create a pull request, you can see the diff of a screenshot.
https://github.com/DroidKaigi/conference-app-2022/pull/471#issuecomment-1247638122
<img width="757" alt="image" src="https://user-images.githubusercontent.com/1386930/190521947-7d26e551-5bba-4bee-94f9-bc5d567a1c7e.png">
But we are using `pull_request` hook that uses the forked repository's TOKEN. So you can't post a comment to the pull request.
We should separate workflow to post a comment.
I think if we download the artifact and move comment to a new workflow, we can fix it.
https://github.com/DroidKaigi/conference-app-2022/blob/main/.github/workflows/ScreenShotTest.yml#L48-L55

There is a similar sample in the GitHub blog. Please see `CommentPR.yml`.
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Reference images and links**
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

**Comment by kwmt** [comment]
I'd like to try this 🙋🏻
