### ISSUE TITLE
Activate ModifierComposable twitter/compose-rules  and fix `./gradlew composeLint`

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#511]
**Idea Description**
The title says everything.

**Reference images and links**
https://twitter.github.io/compose-rules/rules/
https://github.com/DroidKaigi/conference-app-2022/blob/main/detekt.yml#L30-L31

**Comment by h6ah4i** [comment]
:raising_hand_man: There is no code that violates this lint rule for now, so I'll create a PR just to activate this.

**Comment by takahirom** [comment]
It's ok!
Lont time no see!

**Comment by h6ah4i** [comment]
Yeah, it's been so long :smiley:
Here's the PR #544
