### ISSUE TITLE
Activate ModifierMissing twitter/compose-rules and fix `./gradlew composeLint`

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#512]
**Idea Description**
The title says everything.
You can activate it in https://github.com/DroidKaigi/conference-app-2022/blob/main/detekt.yml
And please fix `./gradlew composeLint`.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/detekt.yml
https://twitter.github.io/compose-rules/rules/

**Comment by h6ah4i** [comment]
I'll take this issue :raising_hand_man:

**Comment by takahirom** [comment]
Thanks!

**Comment by h6ah4i** [comment]
ref.) [Chris Banes - Always provide a Modifier parameter](https://chris.banes.dev/always-provide-a-modifier/)
