### ISSUE TITLE
Activate MutableParams twitter/compose-rules and fix `./gradlew composeLint`

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#516]
**Idea Description**
You can activate it in https://github.com/DroidKaigi/conference-app-2022/blob/main/detekt.yml
And please fix `./gradlew composeLint`.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/detekt.yml
https://twitter.github.io/compose-rules/rules/

**Comment by tatsuyafujisaki** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks again!
