### ISSUE TITLE
Add KaigiTag Preview function

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#532]
**Idea Description**
I think it would be useful!

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/ad088a094d1bfd0f2d5b38e555b3b8316c1b2ff7/core-designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/designsystem/components/KaigiTag.kt#L22

**Comment by misuzz** [comment]
May I try this one?

**Comment by takahirom** [comment]
Thanks! Assigned 👍
