### ISSUE TITLE
Add KaigiTopAppBar Preview Composable function

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#533]
**Idea Description**
Adding the Preview function will improve our development efficiency!

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/core-designsystem/src/androidMain/kotlin/io/github/droidkaigi/confsched2022/designsystem/components/KaigiTopAppBar.kt

**Comment by engabesi** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
