### ISSUE TITLE
Fix ExplicitApi in core-data

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#536]
**Idea Description**
Please add `public` if it is used in other classes, if not, please add private for all classes, property, and functions.
<img width="627" alt="image" src="https://user-images.githubusercontent.com/1386930/190842535-18e16484-34f4-4c96-a8c4-11ffa949e447.png">

**Reference images and links**
https://kotlinlang.org/docs/whatsnew14.html#explicit-api-mode-for-library-authors

**Comment by kumokumot** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned!
