### ISSUE TITLE
Hide the keyboard when the Drawer menu is expanding.

### ISSUE THREAD

**Issue by nyafunta9858** [DroidKaigi/conference-app-2022#551]
**Idea Description**
We can expand the Drawer menu even though it shows the software keyboard.
But I think this state is not good whether to input the keyboard or select a menu item from the Drawer menu.

So I suggest you hide the software keyboard when the Drawer menu opens.

**Reference images and links**

<img src=https://user-images.githubusercontent.com/5121183/190866384-882ded04-800e-422c-9a68-bcf2f974bf46.png  width=30%>

**Comment by takahirom** [comment]
Good catch!

**Comment by nyafunta9858** [comment]
Thanks!
And I'd like to try this🙋‍♂️

**Comment by takahirom** [comment]
Thanks!
