### ISSUE TITLE
[iOS] Apply MapView design

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#555]
**Idea Description**

- Apply MapView design

**Reference images and links**

<img width="176" alt="スクリーンショット 2022-09-19 12 51 57" src="https://user-images.githubusercontent.com/30540303/190947137-2488d1fe-e138-41b5-9647-adb0b4b1ae9d.png">

**Comment by HikaruSato** [comment]
I'd like to try this issue. 🖐

**Comment by ry-itto** [comment]
@HikaruSato 
Thanks! Assigned👍

**Comment by ry-itto** [comment]
> I have a question🙋‍♂️
> 
> 
> 
> Should I implement it like the PR below?
> 
> 
> 
> https://github.com/DroidKaigi/conference-app-2022/pull/617/

Yes!
