### ISSUE TITLE
[iOS] Apply NotificationView design

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#556]
**Idea Description**

- Apply NotificationView design

**Reference images and links**
<img width="182" alt="スクリーンショット 2022-09-19 12 51 30" src="https://user-images.githubusercontent.com/30540303/190947077-eeaa4b8f-f0b0-4359-9bdc-b7bb328f845b.png">

**Comment by fummicc1** [comment]
🙋‍♂️

**Comment by ry-itto** [comment]
I'm sorry. I missed🙇‍♂️

@fummicc1 
Assigned!

**Comment by fummicc1** [comment]
Hello! I found that `Announcement` which has same meaning as `Notification` for iOS is used within Android, so let me change its module name from NotificationFeature to AnnouncementFeature. How do you think of it?🙏

- Kotlin Implementation
https://github.com/DroidKaigi/conference-app-2022/pull/631

**Comment by ry-itto** [comment]
👀
you're right!
Please change that!
