### ISSUE TITLE
[iOS] Open access page from AboutPage

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#557]
**Idea Description**

- Title says all
- Open map url is also okey.

**Reference images and links**
- no design of access page is available
- map url: `https://goo.gl/maps/NnqJr2zUVdrAJseH7`

**Comment by betat** [comment]
I'd like to try this issue. 🙋

**Comment by ry-itto** [comment]
@betat 
thanks! Assigned👍
