### ISSUE TITLE
[iOS] Apply SponsorView design

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#558]
**Idea Description**

- Title says all

**Reference images and links**
<img width="184" alt="スクリーンショット 2022-09-19 12 50 38" src="https://user-images.githubusercontent.com/30540303/190947008-fb7962ad-3cda-4812-9816-d8021090a144.png">

**Comment by sudachi808** [comment]
🙋

**Comment by ry-itto** [comment]
@sudachi808 
Thanks! Assigned 👍🏼
