### ISSUE TITLE
[iOS] Open PrivacyPolicy URL Link from `AboutView`

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#560]
**Idea Description**

- Please implement opening privacy-policy URL from `AboutView`

**Reference images and links**

PrivacyPlicy URL: `https://portal.droidkaigi.jp/about/privacy`

**Comment by onakama** [comment]
I try it.🙋‍♀️

**Comment by ry-itto** [comment]
@onakama 
Thanks! Assigned 👍🏼
