### ISSUE TITLE
Apply id("droidkaigi.primitive.detekt") to core-designsystem and fix `./gradlew composeLint`

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#565]
**Idea Description**
Please add the plugin here and fix the lint errors by `./gradlew composeLint`.
https://github.com/DroidKaigi/conference-app-2022/blob/96681626f9385f0e9f1a15cbbb2a9d07610cfb92/core-designsystem/build.gradle.kts#L4

**Reference images and links**

**Comment by higekick** [comment]
🙋🏻‍♂️ Can I take this ?

**Comment by takahirom** [comment]
Thanks! Assigned🙏
