### ISSUE TITLE
Use explicitApi() instead of explicitApiWarning() in core-model and fix build.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#566]
**Idea Description**
If you use explicitApi(), it will cause errors. So please use public to classes, functions, and properties if it is used by other classes. Otherwise, please use private signature.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/core-model/build.gradle.kts#L11

**Comment by tarumzu** [comment]
I'd like to take over this issue

**Comment by takahirom** [comment]
Thanks! Assigned 👍
