### ISSUE TITLE
Apply search item design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#588]
**Idea Description**
I think we can use the session list item.

**Reference images and links**
<img width="219" alt="image" src="https://user-images.githubusercontent.com/1386930/190914353-5953418f-7e6f-460b-955f-32134596535e.png">
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by Corvus400** [comment]
I would like to work on this task.

**Comment by takahirom** [comment]
Thanks as always!

**Comment by Corvus400** [comment]
@takahirom 
Please allow me to confirm my concerns.
Is the corresponding range for this task red or blue?
![スクリーンショット 2022-09-19 10 35](https://user-images.githubusercontent.com/13657682/190937713-a6d6a9d6-b7be-45ee-9344-107958c0f975.png)

**Comment by takahirom** [comment]
@Corvus400 Yes. Currently, I'm arranging the issues.
