### ISSUE TITLE
Apply search text field design

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#594]
**Idea Description**
The title says everything.

**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/190938392-1f67c3b0-2b5b-4ff8-bedc-745c88bb8f80.png)
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by shxun6934** [comment]
I will try this issue.🙋‍♂️

**Comment by mitohato14** [comment]
Thanks! Assigned :+1:
