### ISSUE TITLE
Add empty  search screen function when no exists results

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#597]
**Idea Description**
The title says everything 🙏 

**Reference images and links**
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1
![image](https://user-images.githubusercontent.com/1386930/190939295-f20953bd-66b3-4648-a34c-b03d1aa9d224.png)

**Comment by nyafunta9858** [comment]
I'd like to try! 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by nyafunta9858** [comment]
Please help me 🙏 
I have already implemented almost this issue, but I would like to need advice on adjusting the vertical position.

The reference image specifies the vertical center of the device screen.
I want to place the empty screen to the content of `Scaffold,` but if I put it to the content of `Scaffold,` I can't place the vertical center of the device screen even if I specify `Alignment.Center` to the empty screen.
Could you please advise me if you have some solution?

https://github.com/DroidKaigi/conference-app-2022/pull/755/files#diff-694c80e2460aa28f6068b49f9c0e31d97b8c7b8617f6eaf27b93ba36ea45e45fR515
