### ISSUE TITLE
Add timetable item padding

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#598]
**Idea Description**
We have aligned the items to the line, but it seems a little tight. So we will add padding for it.
https://github.com/DroidKaigi/conference-app-2022/issues/368

**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/190939496-c724e2d5-3ec0-43fb-964e-a65aca978da8.png)

**Comment by CookieySun** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
