### ISSUE TITLE
Add search category filter and day filter bottom sheet

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#600]
**Idea Description**
Please add it. 🙏 

**Reference images and links**
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1
![image](https://user-images.githubusercontent.com/1386930/190940123-6625ffc8-580a-425b-b5ea-f77aa9db17b5.png)

**Comment by surajsau** [comment]
I would like to try 🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
