### ISSUE TITLE
Add session detail message

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#601]
**Idea Description**
There can be a session that is canceled.
We need to inform to attendees.
So Please add the text under the title when there is a Session.message field.
We need this feature by 9/23.

**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/190940760-d6a0df94-bf47-407b-9e7e-f40e542964c9.png)
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=1977%3A10268

**Comment by Corvus400** [comment]
I would like to get started on this task.

**Comment by takahirom** [comment]
Thanks! Assigned! You are so reliable 😄
