### ISSUE TITLE
[iOS] Add session detail message

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#602]
**Idea Description**

- https://github.com/DroidKaigi/conference-app-2022/issues/601 for iOS

**Reference images and links**
- https://github.com/DroidKaigi/conference-app-2022/issues/601

**Comment by Tech-Nayuta** [comment]
I'll take on this issue.

**Comment by sudachi808** [comment]
🙋

**Comment by sudachi808** [comment]
> @Tech-Nayuta Thanks! Assigned 👍🏼
> 
> @sudachi808 @Tech-Nayuta raised his hand first. Therefore, I would appreciate it if you could cooperate with other issues 🙏🏼

🙇
