### ISSUE TITLE
[iOS] Apply SearchView Cell design

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#604]
**Idea Description**

- Currently, SearchView's cell doesn't show session time and cancellation label. Please show session time and that label.

**Reference images and links**

<img width="167" alt="スクリーンショット 2022-09-19 12 55 48" src="https://user-images.githubusercontent.com/30540303/190947445-d223b6a9-8d9d-4442-b324-315878640947.png">

**Comment by yamanetaisei** [comment]
I'd like to try this issue. 🖐

**Comment by ry-itto** [comment]
@yamanetaisei 
Thanks! Assigned 👍
