### ISSUE TITLE
[iOS] Add Search Selection to SearchView

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#605]
**Idea Description**

- Please add selections to SearchView.
- In iOS, these components and bottom sheet implementations are a little difficult. So you can implement with `Menu` or suitable one 👍🏼 

**Reference images and links**
<img width="176" alt="スクリーンショット 2022-09-19 12 57 03" src="https://user-images.githubusercontent.com/30540303/190947559-ba6cbea7-7558-4444-b1af-c381ee2e520f.png">

**Comment by Tomoya113** [comment]
🤚

**Comment by ry-itto** [comment]
@Tomoya113 
Thanks! Assigned 👍🏼

**Comment by ry-itto** [comment]
@Tomoya113 
Thanks for working on this issue. This is an issue to be done by next Friday. Can I ask if you think you will have time to develop it?

**Comment by Tomoya113** [comment]
@ry-itto 
Thank you for the notification.
I am currently working on this issue and have enough time to implement this feature.
If I unable to handle this issue by some reason, I will let you know.

**Comment by Tomoya113** [comment]
@ry-itto 
Sorry for the late.
I just opened PR.
https://github.com/DroidKaigi/conference-app-2022/pull/815
