### ISSUE TITLE
[iOS] Highlight `searchText` match part in SearchView's cell

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#606]
**Idea Description**

- The new design should highlight the parts that match the search string. Please implement that.

**Reference images and links**
<img width="178" alt="スクリーンショット 2022-09-19 13 00 17" src="https://user-images.githubusercontent.com/30540303/190947711-27ccb6ce-6f83-43ef-bc65-bd474fd537cd.png">

**Comment by HikaruSato** [comment]
I'd like to try this issue. 🖐

**Comment by ry-itto** [comment]
@HikaruSato 
Thanks! Assigned 👍

**Comment by HikaruSato** [comment]
I made a PR🙏
