### ISSUE TITLE
[iOS] Add empty view for search result

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#607]
**Idea Description**

- Please add empty view for search result.

**Reference images and links**
<img width="181" alt="スクリーンショット 2022-09-19 13 02 02" src="https://user-images.githubusercontent.com/30540303/190947996-aec8c87b-12bf-4682-bdd7-08fa0dea7398.png">

**Comment by NakaokaRei** [comment]
I'd like to try this issue!
