### ISSUE TITLE
Make Hours and Rooms scrollable

### ISSUE THREAD

**Issue by usuiat** [DroidKaigi/conference-app-2022#608]
**Idea Description**
It would be nice if Hours composable and Rooms composable were scrollable.

- Hours composable should be able to scroll vertically.
- Rooms composable should be able to scroll horizontally.

**Reference images and links**
<img src="https://user-images.githubusercontent.com/17829294/190940129-2a9b37a1-4fc7-44ee-aa3f-07f58b260e15.png" width="300px">

**Comment by takahirom** [comment]
I think It's a great idea!👍
