### ISSUE TITLE
[iOS] SponsorView scroll is stuttering when images are loading

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#643]
**Idea Description**

- Currently, SponsorView scroll is stuttering. Please fix that 🙏🏼 

**Reference images and links**

https://user-images.githubusercontent.com/30540303/191462072-dd5dd552-c58b-45e9-83a6-05e8fc377d12.mp4

**Comment by HikaruSato** [comment]
I want to challenge🙋‍♂️

**Comment by ry-itto** [comment]
@HikaruSato 
Thanks! Assigned 👍🏼

**Comment by HikaruSato** [comment]
@ry-itto 
Sorry, I tried it but it seemed difficult.😭

The size of the logo image (sponsorLogo) returned from the sponsor api(https://ssot-api-staging.an.r.appspot.com/events/droidkaigi2022/sponsor) is 2572 × 1322 pixels, which I think is too large for thumbnail display.
So, if I make this image size smaller (ex. half 1286 x 661), I think it will improve more, but is that impossible?

**Comment by HikaruSato** [comment]
> The size of the logo image (sponsorLogo) returned from the sponsor api(https://ssot-api-staging.an.r.appspot.com/events/droidkaigi2022/sponsor) is 2572 × 1322 pixels,

For example this
https://droidkaigi.jp/2022/images/sponsors/google.png

**Comment by woxtu** [comment]
👀

**Comment by sudachi808** [comment]
I tried down sampling through Kingfisher's Downsampling​Image​Processor. But the app crashed....
(I might have to do the wrong use)

https://kingfisher.onevcat.com/downsamplingimageprocessor/

**Comment by woxtu** [comment]
Hmm...

**Comment by sohichiro** [comment]
I think my suggestion is not best way, but I could resolve this situation.
I inserted ImagePrefetcher on refresh action Reducer like that, and this situation was disappeared.

```
case .refresh:
        state.isLoading = true
        return .run { @MainActor subscriber in
            for try await result: [Sponsor] in environment.sponsorsRepository.sponsors().stream() {
                await subscriber.send(
                    .refreshResponse(
                        TaskResult {
// insert ImagePrefetcher here
                            _ = ImagePrefetcher.init(urls: result.compactMap{URL(string: $0.logo)}, options: nil)
                            return result
                        }
                    )
                )
            }
        }
        .receive(on: DispatchQueue.main.eraseToAnyScheduler())
        .eraseToEffect()
```

**Comment by HikaruSato** [comment]
@sohichiro thank you for your  suggestion 🙏
I'll try.
