### ISSUE TITLE
Add GitHub Action to delete old `companion_` branch

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#650]
**Idea Description**

The `companion_` branch is for saving Compose preview diff images.
But we have to remove the branches for repository size.
So I would like to delete the old branch. Say 2 weeks ago commit or older.
For DroidKaigi, it is not needed. But if we introduce this preview mechanism to the production application, this is needed.

**Reference images and links**

**Comment by higekick** [comment]
Could you let me try this issue ? 🙋🏻‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned🙏
