### ISSUE TITLE
Search screen edge to edge

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#671]
**Idea Description**
I would like to apply window insets properly!

**Reference images and links**
App
<img width="279" alt="image" src="https://user-images.githubusercontent.com/1386930/191762021-0a4c3976-3777-4393-9007-750f6cb4107d.png">
Design
<img width="222" alt="image" src="https://user-images.githubusercontent.com/1386930/191762155-f86b3f6d-c5c0-4886-815e-4f9092aa6233.png">

**Comment by takathemax** [comment]
I'd like to try this issue. 🙋🏼

**Comment by takahirom** [comment]
Thanks!
