### ISSUE TITLE
Toggle search day and category when click around

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#673]
**Idea Description**
Please see the image

**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/191764226-7bfa5eb2-fb7b-487f-8a46-ed1eb71b6704.png)

**Comment by Corvus400** [comment]
I would like to do this task.

**Comment by takahirom** [comment]
Thanks! Assigned 👍
