### ISSUE TITLE
Please close bottom sheet when you click search text field

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#675]
**Idea Description**
Currently, we can see the keyboard with the bottom sheet⌨️ 

**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/191766390-3c722fae-6e94-4b3c-8bb0-1d8f6d825860.png)

**Comment by nanaten** [comment]
✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
