### ISSUE TITLE
Ignore case for search

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#676]
**Idea Description**
If we want to search Compose. We can't search `compose`. We should search `compose`.
Can we make it ignore case?

**Reference images and links**
<img width="289" alt="image" src="https://user-images.githubusercontent.com/1386930/191768482-dbb9e90b-93f5-4dee-927b-57ea2750ab08.png">

**Comment by CookieySun** [comment]
I would like to try.

**Comment by takahirom** [comment]
Thanks! Assigned🙏
