### ISSUE TITLE
Delete composition locals like LocalShareManager and LocalCalendarRegistration and make it event.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#678]
**Idea Description**
This pattern makes it difficult to reuse the screen component. Because it rely implicitly on the Composition Locals.

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/f4d329a3e67902d514db0fcdd6be13d83998ab5c/feature/sessions/src/main/java/io/github/droidkaigi/confsched2022/feature/sessions/SessionDetail.kt#L94

**Comment by higekick** [comment]
I would like to try!✋

**Comment by takahirom** [comment]
Thanks!
