### ISSUE TITLE
[Needed by today 9/23] Apply floor map image

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#688]
**Idea Description**
If you can't do it, our staff will do this tomorrow.

**Reference images and links**
<img width="385" alt="image" src="https://user-images.githubusercontent.com/1386930/191886936-197f0e22-d12f-433e-ac46-2dffafd4eaea.png">
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by kubode** [comment]
Can I take this? ✋

**Comment by RyuNen344** [comment]
Thanks!!! assinged!!!!
