### ISSUE TITLE
Pinch and zoom for floor map

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#706]
**Idea Description**
The title says everything

**Reference images and links**
<img width="194" alt="image" src="https://user-images.githubusercontent.com/1386930/192004853-3cac830d-33bf-41a6-9357-7fa1d42a0f13.png">

**Comment by att55** [comment]
@takahirom Many apologies for last issue. 🙇🏼 
Could I try this issue?
If you'd like, I will get right on it.

**Comment by takahirom** [comment]
I know not everyone always sees GitHub. It's OK. But if you can respond, please respond. 🙏   Thanks, Assigned 👍

**Comment by att55** [comment]
I will check Github from now on. 🙇🏼 
Thanks for assigning!
