### ISSUE TITLE
Change day filter from radio button to checkbox

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#707]
**Idea Description**
We can't uncheck filter so we would like to make it checkboxes
![image](https://user-images.githubusercontent.com/1386930/192005077-872f861a-7af2-47e3-8c75-1f4548ca5ba7.png)

**Reference images and links**

**Comment by Corvus400** [comment]
I would like to start on this issue.

**Comment by takahirom** [comment]
Thanks!
