### ISSUE TITLE
Session detail screen's FloatingActionButton should not be floating

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#708]
**Idea Description**
Please use `FloatingActionButtonDefaults.bottomAppBarFabElevation()` to remove the elevation.

figma
<img width="263" alt="image" src="https://user-images.githubusercontent.com/1386930/192005851-3bd0af8b-8425-4cfd-9da0-c82d79ccf6a8.png">

**Reference images and links**
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by ked4ma** [comment]
i'll do ✋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
