### ISSUE TITLE
Apply fab icon size in session detail.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#709]
**Idea Description**
figma's icon looks bigger than the current app's icon.

**Reference images and links**
<img width="142" alt="image" src="https://user-images.githubusercontent.com/1386930/192006244-078bb88d-a33a-4686-a93f-4e2e4e1b0514.png">

https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by hiwa0** [comment]
I'd like to try this issue.

**Comment by takahirom** [comment]
Thanks! Assigned
