### ISSUE TITLE
Use map icon instead of ▲ in session detail

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#710]
**Idea Description**
Title says everything

**Reference images and links**
<img width="277" alt="image" src="https://user-images.githubusercontent.com/1386930/192006313-8cea07b1-303d-44ac-97db-00edd0521c88.png">
https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1

**Comment by hiwa0** [comment]
I'd like to try this issue.

**Comment by takahirom** [comment]
Thanks! Assigned.
