### ISSUE TITLE
Add current time line on Timetable

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#711]
**Idea Description**
It must be fun 👍 

**Reference images and links**
<img width="583" alt="image" src="https://user-images.githubusercontent.com/1386930/192006973-428e40fe-3a88-4a73-8ef2-a4d8f47642d9.png">

**Comment by iiinaiii** [comment]
I would like to try this issue 🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍
