### ISSUE TITLE
Allow multiple dates to be selected in search filter

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#720]
**Idea Description**
If you have selected Day1 and you select Day2, the filter will be Day2.
I would like to select Day1 or Day2.

**Reference images and links**
<img width="440" alt="image" src="https://user-images.githubusercontent.com/1386930/192082641-76d8741e-e8ab-4498-81ab-99fc409486e9.png">

**Comment by ked4ma** [comment]
I wanna try this ✋
