### ISSUE TITLE
Handle multiple URL in announcement

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#721]
**Idea Description**
Current implementation always uses the first URL in announcement. So If we have multiple URLs in the announcement, it does not work.
https://github.com/DroidKaigi/conference-app-2022/pull/719

**Reference images and links**
https://twitter.com/Fumiya_Kume/status/1573523409707085824

**Comment by Corvus400** [comment]
I will do it myself, as this is where I originally implemented it.

**Comment by takahirom** [comment]
I think we should use buildAnnotatedString{} and iterate the link inside.
Something like this..

```kotlin
var lastIndex = 0
buildAnnotatedString{
  while(linkPattern.hasNext()) {
    val pattern = linkPattern.next()
    body.subtring(lastIndex,pattern.index) + addStringAnnotation(...)
  }
}
```


https://stackoverflow.com/a/65656351/4339442

**Comment by Corvus400** [comment]
Thank you!
I was trying to implement this in the morning with the help of the information ( https://stackoverflow.com/a/69549929 ) around here, but it didn't work and I gave up.
I will try again, including your advice.

**Comment by Corvus400** [comment]
@takahirom 
I have a question. 🙋‍♂️
Is the following pattern the only text string in the body of the notice delivered from the server side?

"Click here for more information" (non-URL string)
"https://droidkaigi.jp/2022"(URL string)

Are the following patterns also available?

"https://droidkaigi.jp/2022"(URL string)
"some text" (non-URL string)

**Comment by takahirom** [comment]
I think there can be both of patterns.

The xxx event is here. Please register
https://xxx

If you interested...
https://yyy

**Comment by fumiya-kume** [comment]
From @Corvus400 's [tweet](https://twitter.com/Todayama_R/status/1573582762589581312?s=20&t=K_y-S0mSB2HT668wptwV1Q).
Basically I agree with @takahirom 's [comment](https://github.com/DroidKaigi/conference-app-2022/issues/721#issuecomment-1256890457)

I'd recommend to consider a11y perspective improvements as well.

From feature requirements perspective, current implementation with `AnnotatedString` way should working well.

**Idea 1: Apply Link style to target link text.** 

I means, you can adding the `Underbar` + kinder blue text color(Link text style as we familiar)  to easy to recognize the link.

**Idea2: Adding the button to open the link.**

`AnnotatedString` way will solve the multi link situation, also we can use the sufficiently font size for a11y. but it's difficult to caring whole cases. so I'd like to recommend to adding the button for opening the each link.

it's example for my idea 2.
 
<img width="753" alt="スクリーンショット 2022-09-24 18 21 13" src="https://user-images.githubusercontent.com/16269075/192090512-34044647-4719-4b0a-8eef-171e1b367d40.png">

Thank you for host my through to discussion.
