### ISSUE TITLE
[Sponsors] Show Loading indicator during fetching sponsors logo

### ISSUE THREAD

**Issue by fumiya-kume** [DroidKaigi/conference-app-2022#727]
**Idea Description**

## Current situation

Just showing the logo, nothing showing until fetching image

## Ideal situation

Showing the loading indicator until fetching image 

# Discussion points

- Implement the loading indicator logic is simple, but we can consider to commonize to the app. 

**Reference images and links**

- [source](https://github.com/DroidKaigi/conference-app-2022/blob/main/feature/sponsors/src/main/java/io/github/droidkaigi/confsched2022/feature/sponsors/Sponsors.kt#L194-L198)
- [Coil reference](https://coil-kt.github.io/coil/compose/#subcomposeasyncimage)

**Comment by HiroyukiTamura** [comment]
🙋 let me try this issue
I'll implement it with [Accompanist placholder](https://google.github.io/accompanist/placeholder/)

**Comment by takahirom** [comment]
@HiroyukiTamura Great. Assigned 👍
