### ISSUE TITLE
Crash contributors screen when error happens

### ISSUE THREAD

**Issue by fumiya-kume** [DroidKaigi/conference-app-2022#728]
**Describe the bug**

We didn't handle the error on Contributors screen also nothing ticket to implement it.

**To Reproduce**

1. Turn on the AirPlace mode
2. Go to contributors screen
3. App crash

**Expected behavior**

Showing the toast or something instead of app will crash at [here](https://github.com/DroidKaigi/conference-app-2022/blob/main/feature/contributors/src/main/java/io/github/droidkaigi/confsched2022/feature/contributors/Contributors.kt#L69)

**Screenshots**

**Comment by takahirom** [comment]
This is exactly what I am working on these days.
If you interested in this issue, please take a look at these pull requests
https://github.com/DroidKaigi/conference-app-2022/pull/718

**Comment by takahirom** [comment]
I think this will happen in staff screen as well. I will create the issue.

**Comment by fumiya-kume** [comment]
Up to someone who interest to implement it!

**Comment by takahirom** [comment]
This is handled in https://github.com/DroidKaigi/conference-app-2022/pull/767
