### ISSUE TITLE
Improve Schedule list screen for same schedule 

### ISSUE THREAD

**Issue by fumiya-kume** [DroidKaigi/conference-app-2022#729]
**Idea Description**

## Current situation

Currently the schedule list screen showing same schedule multiple time.

Welcome talk | Lunch
:--: | :--:
<img src="https://user-images.githubusercontent.com/16269075/192092365-9c323417-349c-42e9-931d-503ec8d965cb.png" width="300" /> | <img src="https://user-images.githubusercontent.com/16269075/192092364-94baf4cb-8d76-42fd-8854-afee205c80b7.png" width="300" />

## Ideal situation

Showing the same schedule for 1 row(kinder combined to 1 schedule).

**Reference images and links**

**Comment by takahirom** [comment]
That definitely make sense. But they can be different a little. For example, there is no translation for online welcome talk. I think it is difficult to handle the difference. Let me know if there is any way to handle well.

**Comment by fumiya-kume** [comment]
> I think it is difficult to handle the difference. Let me know if there is any way to handle well.

Got it, that's should separated for avoid confusion!

BTW, how about the lunch schedules? looks same for each item?(difference are only room, right?

**Comment by takahirom** [comment]
For now, yes. And probably you are right. But it is difficult to imagine the changes.😅

**Comment by takahirom** [comment]
Let me close this issue until the better way is found.
