### ISSUE TITLE
Fix deleting screenshot GitHub Action job

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#734]
**Idea Description**

https://github.com/DroidKaigi/conference-app-2022/blob/main/.github/workflows/CommentPR.yml#L106

```
fatal: not a git repository (or any of the parent directories): .git
Error: Process completed with exit code 128.
```

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/actions/runs/3117853645/jobs/5056772576

**Comment by nashcft** [comment]
🙋

**Comment by takahirom** [comment]
Thanks! Assigned 👍 You can check it by creating test pr.

**Comment by nashcft** [comment]
I think #754 resolved this issue:

https://github.com/DroidKaigi/conference-app-2022/actions/runs/3122425253/jobs/5064355002

**Comment by takahirom** [comment]
Looks great! Thanks!
