### ISSUE TITLE
Improve Timetable performance by making it stable.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#761]
**Idea Description**

I think we can use PersistentList. for timetableListStates and days

```
restartable scheme("[androidx.compose.ui.UiComposable]") fun Timetable(
  stable pagerState: PagerState
  unstable timetableListStates: List<TimetableState>
  stable schedule: DroidKaigiSchedule
  unstable days: Array<DroidKaigi2022Day>
  stable onTimetableClick: Function1<TimetableItemId, Unit>
  stable modifier: Modifier? = @static Companion
  stable contentPadding: PaddingValues? = @static PaddingValues()
)
```

**Reference images and links**

**Comment by eneim** [comment]
Question: how did you get this output

```
restartable scheme("[androidx.compose.ui.UiComposable]") fun Timetable(
  stable pagerState: PagerState
  unstable timetableListStates: List<TimetableState>
  stable schedule: DroidKaigiSchedule
  unstable days: Array<DroidKaigi2022Day>
  stable onTimetableClick: Function1<TimetableItemId, Unit>
  stable modifier: Modifier? = @static Companion
  stable contentPadding: PaddingValues? = @static PaddingValues()
)
```

Is that your decomposer plugin or something else? It is so useful to see what is stable and what is not.

**Comment by takahirom** [comment]
Sorry, I enabled it in gradle.properties. 
https://github.com/DroidKaigi/conference-app-2022/blob/main/gradle.properties#L44-L45

The option is used here
https://github.com/DroidKaigi/conference-app-2022/blob/main/gradle/plugins/src/main/kotlin/io/github/droidkaigi/confsched2022/primitive/AndroidComposePlugin.kt#L42-L64

So you can see the results build/compose-metrics and build/compose-reports each compose module.

**Comment by takahirom** [comment]
The output is here.
feature/sessions/build/compose-reports/sessions_debug-classes.txt

**Comment by eneim** [comment]
Thanks. Learn new thing today ❤️ .

**Comment by kmachida12345** [comment]
Is anyone working on this issue? 👀 
Could I give it a try?  🙋‍♂️

**Comment by takahirom** [comment]
@kmachida12345 Thanks! Assigned 👍
