### ISSUE TITLE
Problem with import order differs between Android Studio and KtLint

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#77]
Formatting imports in Android Studio with SessionsViewModel causes this problem. 
I believe it is probably a KtLint or Spotless configuration issue.

**Comment by kafumi** [comment]
Could I take this issue? I think we can fix the issue by setting a EditorConfig property.
https://pinterest.github.io/ktlint/rules/configuration-ktlint/#import-layouts

**Comment by takahirom** [comment]
This is a very annoying issue. If you fix this we are happy 🙏
