### ISSUE TITLE
[iOS] error build: Command PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by fumiyasac** [DroidKaigi/conference-app-2022#785]
**Describe the bug**

When I took in latest diffs in my repository, Xcode project was not able to build.

Error message is below:
`error build: Command PhaseScriptExecution failed with a nonzero exit code`

**To Reproduce**
1. Clone `main` branch or merge `upstream/main` (following your local)
2. Execute scripts `./scripts/build_kmm_framework.sh Debug`
3. Open Xcode Project & Build
4. See Build Error

**Expected behavior**
Xcode project is able to build.

**Screenshots**
![スクリーンショット 2022-09-28 8 47 27](https://user-images.githubusercontent.com/949561/192657282-bc6e1efc-e6d0-4f1c-948c-db125fff037e.png)

**Appendix**

My Environment is below:
- OS: Monterey 12.6
- Xcode: 14.0.1
- Other: M2 Tip

**Comment by ry-itto** [comment]
@fumiyasac 
Can you share your log about this? 🙏🏼 
Maybe this step https://github.com/DroidKaigi/conference-app-2022/tree/main/app-ios#building-prerequisite is missing in your setup 👀

**Comment by fumiyasac** [comment]
@ry-itto 
Thanks. building-prerequisite step seems to miss.
（Unfortunately,`echo $JAVA_HOME` result is blank in my Mac...）

My log is below:
```
♻️  Copying MokoResources...
../../local.properties does not exist, please setup java home location first. If you are unsure how to do that, please consult the app-ios/README.md file
Command PhaseScriptExecution failed with a nonzero exit code
```

[Build DroidKaigi2022 (iOS)_2022-09-28T11-15-38.txt](https://github.com/DroidKaigi/conference-app-2022/files/9661283/Build.DroidKaigi2022.iOS._2022-09-28T11-15-38.txt)

**Comment by fumiyasac** [comment]
### FYI

Here is the command I tried.

```shell
# (1) Check java version.
# *Remark: If you don't display java version, you'll have to install java with installer or homebrew command. 
$ java -version
openjdk version "13.0.12" 2022-07-19
OpenJDK Runtime Environment Zulu13.50+15-CA (build 13.0.12+4-MTS)
OpenJDK 64-Bit Server VM Zulu13.50+15-CA (build 13.0.12+4-MTS, mixed mode)

# (2) export $JAVA_HOME in .zshrc file.
$ echo "export JAVA_HOME=\$(/usr/libexec/java_home -v 13)" >> ~/.zshrc
$ source ~/.zshrc

# (3) Check $JAVA_HOME
/Users/***(Your User Name)***/Library/Java/JavaVirtualMachines/azul-13.0.12/Contents/Home

# (4) Write org.gradle.java.home in local.properties file.
$ cd conference-app-2022/
$ vim local.properties
org.gradle.java.home=/Users/***(Your User Name)***/Library/Java/JavaVirtualMachines/azul-13.0.12/Contents/Home
```

**Comment by ry-itto** [comment]
Okey!
It's good!

I'll close this issue 👍🏼
