### ISSUE TITLE
[iOS] [iOS16] Use NavigationStack instead of navigationViewStyle(.stack)

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#789]
**Idea Description**

- From iOS16, `navigationViewStyle(.stack)` is deprecated, please replace those with `NavigationStack` implementation

**Reference images and links**
- https://developer.apple.com/documentation/swiftui/view/navigationviewstyle(_:)
- https://developer.apple.com/documentation/swiftui/navigationstack

**Comment by coffmark** [comment]
🙋‍♂️

**Comment by ry-itto** [comment]
@coffmark 
Thanks! Assigned 👍🏼
