### ISSUE TITLE
[iOS] Remove MapView's bottom toolbar

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#790]
**Idea Description**

- Title says all. MapView's bottom toolbar isn't needed. So please remove that.

**Reference images and links**
![スクリーンショット 2022-09-28 19 03 32](https://user-images.githubusercontent.com/30540303/192751480-ae585c83-d99a-433c-8ec4-8cd193de3972.png)

**Comment by coffmark** [comment]
🙋‍♂️

**Comment by ry-itto** [comment]
@coffmark 
Thanks! Assigned 👍🏼
