### ISSUE TITLE
Close the drawer when detected for pressing the back key (or back gesture) during the drawer opening.

### ISSUE THREAD

**Issue by nyafunta9858** [DroidKaigi/conference-app-2022#793]
**Idea Description**
- Currently, pop back the screen if detected for the back key press, and the drawer keeps opening.
- I think it's not good UX to transition to the other screen while opening the drawer.
- So I suggest closing the drawer when detected for pressing the back key if that opens.

**Reference images and links**
![record-220929013045](https://user-images.githubusercontent.com/5121183/192835953-5b3abecf-91c5-4192-875b-d7662a8b8686.gif)

**Comment by nyafunta9858** [comment]
🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 👍
