### ISSUE TITLE
[iOS] [iOS16] Use official `ShareLink` view instead of `ShareTextView`

### ISSUE THREAD

**Issue by ry-itto** [DroidKaigi/conference-app-2022#798]
**Idea Description**

- From iOS16, SwiftUI supports `ShareLink`. Please use it instead of `ShareTextView`
- `.sheet(isPresented:)` isn't needed if `ShareLink` is supported.

**Reference images and links**

- https://developer.apple.com/documentation/SwiftUI/ShareLink

**Comment by mhidaka** [comment]
@NakaokaRei Thank you! we assigined you 👍
