### ISSUE TITLE
Unnecessary ellipsis appear on the time-line title

### ISSUE THREAD

**Issue by ohzono** [DroidKaigi/conference-app-2022#802]
**Describe the bug**
Time-line title ellipsis is displayed on first line, but it seems to be better to be displayed at maximum line only.

**To Reproduce**
1. Install from Play Store.  I haven't confirmed yet in development environment.
2. For example, set in Japanese from drawer menu `Setting`.
3. Go to Day 2 time line.
4. See `App bars`'s column at 12:00. There is a session `通知チャンネルに対応する`. 
5. See the behavior of the ellipsis like `通知チャンネルに対応...`.

**Expected behavior**
I think it would be better to show in 2nd line in the above case.
So, I suggest that the ellipsis is appeared just on maximum line.

**Screenshots**
<img src="https://user-images.githubusercontent.com/11993783/192706019-ac9103ae-2f47-412f-ba1f-04cb185ebb61.png" width="300">

**Comment by tatsuyafujisaki** [comment]
It looks like an expected behavior because there is no room for the second line in a 25-minute session. The first line is the last line. Only a 30-minute session or longer has room for the second line.

**Comment by ohzono** [comment]
Thank you for your comment!

>The first line is the last line.

I may understand it but I'm not sure. 
Please confirm following once🙏 
 
What I want to say is it would be better to show full text if there is a **blank line space** to show all sentence edge-to-edge in this `通知チャンネルに対応する` case.

For example, the neighbor time-table `実例から学ぶJetpack Composeのパフォーマンス改善` was shown in 2nd line.
So 25-min session may have space to show 2nd line.

I expected to improve following...

**before:**

```
通知チャンネルに対応...
```

**after:**
```
通知チャンネルに対応
する
```

What do you think about this?

**Comment by tatsuyafujisaki** [comment]
Thanks for the explanation:pray: I got it. Somehow, `"通知チャンネルに対応する"` does not show the second line while `"通知チャンネルに対応するJetpack Compose"` (no meaning) does. I cannot come up with a good solution…

"通知チャンネルに対応する"|"通知チャンネルに対応するJetpack Compose"
--|--
<img src="https://user-images.githubusercontent.com/1838962/193291758-2aa7ac4d-3039-429b-9552-3346c6be5556.png" width="480" />|<img src="https://user-images.githubusercontent.com/1838962/193291763-026fb0c1-7502-4f2a-8b49-eb11222a5de0.png" width="480" />

**Comment by Luecy1** [comment]
The cause seems to be the font.
https://github.com/Luecy1/conference-app-2022/commit/befb0cd71d325011a9d4eaa4ed08774925b7b11c
When I revert the font as above, it was displayed in two lines


<img width="293" alt="スクリーンショット 2022-10-01 14 50 42" src="https://user-images.githubusercontent.com/4579774/193394779-d787d5eb-6ee2-4140-b920-8b33e401044f.png">

But,I not have solution idea.

**Comment by ohzono** [comment]
I'm not familier with Compose view, and I may have no time to fix them by DroidKaigi held 😰 

You may have already tried it, there were some solution in TextView of XML layout. 
https://stackoverflow.com/questions/2160619/android-ellipsize-multiline-textview

Have you confirmed the idea yet? 

If you have done already, it might be good to call for help 🙌

**Comment by ohzono** [comment]
What!? @Luecy1 might have already done?

This issue solved with your idea by tring on my local.
Could you make PR? 

I don't confirm the background of the font decision. 
If it caused by downloadable font, it is a way to open another issue.

Limited my small point of view about this repo, I think it is higher priority than adopt downloadable fonts.
Because it is visible for public users.


Here is the link I saw for your reference. It might be bug of Compose, I don't know.
https://issuetracker.google.com/issues?q=compose%20text%20overflow%20ellipsis

Set maxline idea: it might not be good.
https://stackoverflow.com/questions/65736375/how-to-show-ellipsis-three-dots-at-the-end-of-a-text-line-in-android-jetpack-c

**Comment by Luecy1** [comment]
I didn't create a PR because the app design will change.
I will create PR, not use downloadable font.

**Comment by ohzono** [comment]
Thanks!
