### ISSUE TITLE
Difference of words Annoucement on drawer and the screen's title, it is News

### ISSUE THREAD

**Issue by ohzono** [DroidKaigi/conference-app-2022#803]
**Describe the bug**
In English setting, there is a difference of item name Annoucement on drawer and the screen's title, News.

**To Reproduce**
1. Set in English from drawer menu Setting.
2. Show drawer and see the item `Announcement`.
3. Tap the `Announcement`, and see the showed screen's title.

**Expected behavior**
Decide which is a better word, and set it.

**Screenshots**
<img src="https://user-images.githubusercontent.com/11993783/193044190-e81f8480-b87d-49a8-a812-7598e92b254b.png" width="300"><img src="https://user-images.githubusercontent.com/11993783/193044196-b003e0f1-475a-441a-9e5f-3cdc4f5b8f27.png" width="300">

**Comment by Corvus400** [comment]
This is not a bug but a design specification.
[The wording was changed during implementation to match the design specification.
](https://github.com/DroidKaigi/conference-app-2022/pull/639#pullrequestreview-1114727696)See [Design](https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=0%3A1) for details.

**Comment by ohzono** [comment]
@Corvus400 
Thank you for your response! I understood it and saw the design at the news (or announcement) screen.
I thought the design doc seems not to be described about the drawer's translation.
I don't found the words difference specification is true, but News screen title is true at this time 😄 .

@takahirom 
In this case, I would be better to repost this in feature request format?
I am fine with either, but I am somewhat uncomfortable with the different words from-to.

**Comment by takahirom** [comment]
I'll talk with the designer. 
I'll let you know as soon as I get more information 🙏

**Comment by takahirom** [comment]
The designer tell me it is ok to use `Announcement` 🙏 
Can we use it?

**Comment by ohzono** [comment]
Thank you for your arrangement!
It is good.
I would try to replace `News` into `Announcement` at the title. 🙋🏻

**Comment by takahirom** [comment]
Thanks!
