### ISSUE TITLE
Japanese date format of the day part is ambiguous at Announce screen

### ISSUE THREAD

**Issue by ohzono** [DroidKaigi/conference-app-2022#805]
**Describe the bug**
The title of  announce screen's item, like `2022/09/7` is no zero padding at day part.

**To Reproduce**
1. Set in Japanese from drawer menu Setting.
2. Show drawer.
3. Tap `Announcement`.
4. If there are anoucements, you can see the date text.

**Expected behavior**
It might be better add zero padding at the day part or no zero padding at all.

**Screenshots**
<img src="https://user-images.githubusercontent.com/11993783/193044231-0107f4f1-b4d4-4c76-919c-64efe1327371.png" width="300">

**Comment by takahirom** [comment]
Thanks!

**Comment by Corvus400** [comment]
The URL is not a link either, so it is most likely an older version of the app.

**Comment by takahirom** [comment]
Thanks! I thought it was different screen🙏

**Comment by ohzono** [comment]
I'm sorry and thank @Corvus400 san to fix it, and @takahirom san for response 🙏
