### ISSUE TITLE
Delete target audience in session detail if the target audience is `TBW`

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#814]
**Idea Description**
The title says everything

**Reference images and links**
![image](https://user-images.githubusercontent.com/1386930/193168992-abf2ee93-691a-4cdf-9b79-dc312c95ca0c.png)

**Comment by igafox** [comment]
I would like to try!🙋‍♂️

**Comment by takahirom** [comment]
Thanks! Assigned 🙏
