### ISSUE TITLE
If session start time or end time is longer than screen size session not shown

### ISSUE THREAD

**Issue by gen0083** [DroidKaigi/conference-app-2022#824]
**Describe the bug**
If session start time or end time is longer than screen size session not shown.

**To Reproduce**
1. Go to session page on day3
2. Scroll down to 14:00
3. Scheduled session is not shown

**Expected behavior**
It it better to show that there is a session.

**Screenshots**
![device-2022-10-01-160123 2022-10-01 16_09_05](https://user-images.githubusercontent.com/7608725/193397547-b1560efa-6bc4-4eb2-a2a8-1ed261cba029.gif)

**Comment by takahirom** [comment]
Thanks

**Comment by gen0083** [comment]
I'll take it.

**Comment by takahirom** [comment]
Thanks! Assigned 👍
