### ISSUE TITLE
Change navigation icon in session detail screen

### ISSUE THREAD

**Issue by NUmeroAndDev** [DroidKaigi/conference-app-2022#828]
**Idea Description**
- I want to change close icon to arrow icon in session detail screen.

**Reference images and links**

- https://www.figma.com/file/NcSMs6dMsD88d4wOY0g3rK/DroidKaigi-2022-Conference-App?node-id=21%3A583

<img width="317" alt="スクリーンショット 2022-10-02 13 20 44" src="https://user-images.githubusercontent.com/13705006/193437724-66d492ae-8840-40ec-a882-75622fd7ed10.png">

**Comment by rnk0085** [comment]
🙋

**Comment by NUmeroAndDev** [comment]
@rnk0085 
Thanks! Assigned 👍
