### ISSUE TITLE
Category check mark not checked during session search

### ISSUE THREAD

**Issue by momomomo111** [DroidKaigi/conference-app-2022#849]
**Describe the bug**
Tapping the name of a category during a session search turns on the checkbox, but tapping the checkbox itself does not turn on the checkbox.

**To Reproduce**
1. Go to 'Search'
2. Click on 'Category'
3. Tap the checkbox
4. The checkbox is not checked.

**Expected behavior**
Tap the checkbox itself to check the box.

**Screenshots**

https://user-images.githubusercontent.com/51113946/194061041-4e32d036-e702-4858-b427-a06a7bafacfc.mp4

**Comment by takahirom** [comment]
Good catch!

**Comment by ked4ma** [comment]
i'll do this ✋

**Comment by takahirom** [comment]
Thanks! Assigned👍
