### ISSUE TITLE
Adapt material3 to v1.0.0-rc01

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#860]
**Idea Description**

There is a pull request that is updated by a bot. But there is a preview difference.
So I would like to adjust the design and update!

<img width="685" alt="image" src="https://user-images.githubusercontent.com/1386930/194260305-4bae27a3-1544-48cf-996d-b65d46463070.png">

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/pull/856

**Comment by ked4ma** [comment]
I'll try it 🤚

**Comment by ked4ma** [comment]
I've completed this issue, but it seems that this is not closed automatically. 🤔

**Comment by takahirom** [comment]
Anyway, I'm going to close.

**Comment by ked4ma** [comment]
Thank you so much!!
