### ISSUE TITLE
Use Zipline to display some messages on the "first" Codelabs and Pathways of Day 3.

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2022#871]
**Idea Description**
Use Zipline to display some messages on the first Codelabs and Pathways of Day 3.

"Thank you for your participation."
参加いただきありがとうございました。

**Reference images and links**
https://github.com/DroidKaigi/conference-app-2022/blob/main/core/zipline/src/jsMain/kotlin/io/github/droidkaigi/confsched2022/zipline/JsScheduleModifier.kt

**Comment by takathemax** [comment]
I'd like to work on this issue 🙋🏻

**Comment by RyuNen344** [comment]
thanks!! assigned!!
