### ISSUE TITLE
The navigation bar covers bottom sheet contents

### ISSUE THREAD

**Issue by woxtu** [DroidKaigi/conference-app-2022#893]
**Describe the bug**
As the title says, the navigation bar covers bottom sheet contents.

**To Reproduce**
1. Enable the navigation bar, or run on old devices
2. Go to the search screen
3. Tap the 'Day' button

**Expected behavior**
The navigation bar doesn't cover them.

**Screenshots**
<img src="https://user-images.githubusercontent.com/5673994/194705919-f846ba0f-9790-454d-acea-2c02e845108f.png" width="300" />
(Pixel 2 API 24 Emulator)

**Comment by takahirom** [comment]
Thanks!

**Comment by ked4ma** [comment]
I'll do it 🤚
